### ISSUE TITLE
esparse/esvalidate should accept an options file

### ISSUE THREAD

**Issue by hegemonic** [eslint/espree#122]
The esparse/esvalidate tools don't offer command-line options for many of Espree's config settings, including the ES 2015 flags. As a result, you can't use these tools with ES 2015 source files.

It'd be nice if users could provide a JSON config file to esparse/esvalidate, using the same format as the `options` argument to `espree.parse()`, so that all of Espree's various settings can be changed.

**Comment by nzakas** [comment]
Honestly, I completely forgot those were in there. :) I'm not sure if I really want to maintain them, so I may just remove them.

**Comment by hegemonic** [comment]
Heh, fair enough.

**Comment by nzakas** [comment]
Removed in 3.0.0
