### ISSUE TITLE
Support ES7 Array comprehensions

### ISSUE THREAD

**Issue by smehrbrodt** [eslint/espree#125]
Array comprehensions like

```javascript
[ x for (x of a) if (x.color === ‘blue’) ]
```

should be supported.

Here's more information: http://wiki.ecmascript.org/doku.php?id=harmony:array_comprehensions

It's already supported by Firefox and some transpilers (Babel and Traceur), so we're already using them.

**Comment by nzakas** [comment]
I'll leave this under consideration. We're not going to implement any ES7 features until they are standardized.

**Comment by thetalecrafter** [comment]
I would recommend against using them, because they are at stage 0 (strawman proposal), and may not get standardized.

See:
* https://twitter.com/esdiscuss/status/590226685020090369

**Comment by smehrbrodt** [comment]
Ok, thanks for the clarification. I'll close this issue then.
