### ISSUE TITLE
Rest argument allowed even when `restParams` is false

### ISSUE THREAD

**Issue by andy-hanson** [eslint/espree#130]
This code succeeds:

	require('espree').parse('(arg, ...args) => b', {
		ecmaFeatures: {
			restParams: false,
			arrowFunctions: true,
			destructuring: true,
			spread: true
		}
	})

It requires both `destructuring` and `spread` to be on.
It seems to only happen for arrow functions with a parameter preceding the rest parameter.

**Comment by nzakas** [comment]
Ah yeah, that makes sense. The rest param is initially read as spread and then changes once the arrow is seen. I'll take a look.

**Comment by nzakas** [comment]
Working on this.
