### ISSUE TITLE
[ES7] Basic support for async functions/methods

### ISSUE THREAD

**Issue by julien-f** [eslint/espree#140]
I use them in many projects notably for class methods because the syntax prevents me from easily using workarounds such as `Bluebird.coroutine(function * generator() {})`.
Unfortunately doing so breaks parsing and prevents EsLint from finding other errors.

I understand that fully implementing async functions could be a lot of work and that it is not a priority to support ES7 features for now but a preliminary support such as simply removing them from the source would at least allows the parsing of the rest of the code.

**Comment by lo1tuma** [comment]
As mentioned by @nzakas in https://github.com/eslint/espree/issues/125#issuecomment-97266762
> We're not going to implement any ES7 features until they are standardized.

**Comment by julien-f** [comment]
@nzakas does not seem opposed to implementing this future, as mentioned in https://github.com/eslint/eslint/issues/1657#issuecomment-73770436:
> If you want it, consider adding support to Espree: https://github.com/eslint/espree.
>
>We will get to it, but it's low priority for the core team based on getting the rest of ES6 done. You can make it go faster by contributing. :)

I personally don't know how to implement it and I understand it can be much work, that's why I thought it would be worth proposing a intermediary solution.

**Comment by nzakas** [comment]
I can speak for myself here: we aren't implementing experimental features. If you need such support in ESLint, you can use babel-eslint.

**Comment by nickpoorman** [comment]
This is no longer experimental, is in stage 2, and implemented in Edge. I'm thinking it might be time to support async.

**Comment by xjamundx** [comment]
Stage 3 even? https://github.com/tc39/ecma262/commit/2fa3ca4bbc8e9feece0cce363b076a1942e8c6ba

**Comment by xjamundx** [comment]
Though i assume this will get swallowed up by #200

**Comment by egoroof** [comment]
Want this too. :cry:  Currently I use `babel-eslint` which isn't a good solution - eslint parses transpiled code which I didn't write and catches errors in that.

It's stage 3 which tells about 'Post-Acceptance Changes Expected':

> Limited: only those deemed critical based on implementation experience

**Comment by benjamine** [comment]
+1, would love to avoid `babel-eslint` to use async/await :'(

**Comment by not-an-aardvark** [comment]
@benjamine This issue is a bit out-of-date; if you're using ESLint 3.6.0 or higher, you can now use `parserOptions: {ecmaVersion: 8}` in your config to enable async/await.
