### ISSUE TITLE
Replace esprima-fb in recast

### ISSUE THREAD

**Issue by m1sta** [eslint/espree#144]
How would the espree devs feel about taking up the parser role in recast (and regenerator)?

Discussion here:
https://github.com/benjamn/recast/issues/178

**Comment by xjamundx** [comment]
Personally I've thought about it and they're welcome to use espree in their project, but I'm not able to aid with that project in any meaningful way, even though I think it's a great idea!

**Comment by nzakas** [comment]
We have no problem with recast using Espree. Besides ESLint, JSDoc is also using Espree, so it's getting some pretty good exercise.

**Comment by m1sta** [comment]
In theory it should be just a drop in replacement since esprima-fb and espree use the same api. They'd just need a pull request.

**Comment by nzakas** [comment]
While we are happy to support it, we aren't going to actively participate in recast development, so one of their team members would need to create a pull request.
