### ISSUE TITLE
Support for trailing commas in Import/Export statements

### ISSUE THREAD

**Issue by xjamundx** [eslint/espree#148]
Babel supports this, I need to check with the spec:

- `import {y,} from 'x';` 
- `export {y,} from 'x';`

**Comment by sebmck** [comment]
It's in the spec.

[15.2.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-imports)

> NamedImports :
> { }
> { ImportsList }
> { ImportsList , }

[15.2.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports)

> ExportClause :
> { }
> { ExportsList }
> { ExportsList , }

**Comment by nzakas** [comment]
Thanks @sebmck, we will get this fixed.

**Comment by xjamundx** [comment]
Putting my parser hat back on and fixing this... :tophat:

**Comment by xjamundx** [comment]
`import` case works. Need to add `export`. Will file in the morning!

**Comment by xjamundx** [comment]
Okay should be ready to go
