### ISSUE TITLE
Comment Attachment is confused by comment within condintion

### ISSUE THREAD

**Issue by lo1tuma** [eslint/espree#155]
Given the following code:

```js
/* foo */
if (/* bar */  a) {}
```

produces the following partial AST when `attachComment` is enabled:

```json
{
  "type": "IfStatement",
  "test": {
    "type": "Identifier",
    "name": "a",
    "leadingComments": [
      {
        "type": "Block",
        "value": " foo "
      },
      {
        "type": "Block",
        "value": " bar "
      }
    ]
  },
  "consequent": {
    "type": "BlockStatement",
    "body": []
  },
  "alternate": null
}
```

As you can see both comments are attached to the `Identifier` node of the `IfStatement` test.

If the comment in the test condition is not present, the first comment `foo` is directly attached to the `IfStatement` node. 

```js
/* foo */
if (a) {}
```

```json
{
  "type": "IfStatement",
  "test": {
    "type": "Identifier",
    "name": "a"
  },
  "consequent": {
    "type": "BlockStatement",
    "body": []
  },
  "alternate": null,
  "leadingComments": [
    {
      "type": "Block",
      "value": " foo "
    }
  ]
}
```

I would expect a more reliable behavior of the comment attachment algorithm, so that the first comment `foo` is always attached to the same node (preferable the `IfStatement` node).

Same problem exists for `WhileStatement` and I would guess `ForStatement`, `ForInStatement`, and `ForOfStatement`.

**Comment by nzakas** [comment]
Agreed, seems like a bug. Comment attachment is hard.
