### ISSUE TITLE
Implement new.target

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#157]
This is the one thing we missed from ES6, the `new.target` metaproperty. The option name should be `newTarget`.

AST definition: https://github.com/estree/estree/blob/master/es6.md#metaproperty

**Comment by nzakas** [comment]
Related: https://github.com/jquery/esprima/pull/1216

**Comment by nzakas** [comment]
Working on this.

**Comment by xjamundx** [comment]
I just read about this in your :book: !
