### ISSUE TITLE
``leadingComments`` of anonymous class export are broken.

### ISSUE THREAD

**Issue by h13i32maru** [eslint/espree#158]
Hi! I use Espree in [ESDoc](https://github.com/h13i32maru/esdoc).

A ``leadingComments`` position are unexpected, when I parse following code with Espree.

```javascript
/**
 * this is anonymous class.
 */
export default class {
  /**
   * this is method1.
   */
  method1(){
  }
}
```
<img width="486" alt="2015-07-05 12 06 17" src="https://cloud.githubusercontent.com/assets/985170/8510151/49c8d898-230e-11e5-8bff-99a130e48cb3.png">

(full JSON https://gist.github.com/h13i32maru/f22536ca8c224e08cc9e)

Espree option:
```javascript
  {
      comments: true,
      attachComment: true,
      loc: true,
      ecmaFeatures: {
        arrowFunctions: true,
        blockBindings: true,
        destructuring: true,
        regexYFlag: true,
        regexUFlag: true,
        templateStrings: true,
        binaryLiterals: true,
        octalLiterals: true,
        unicodeCodePointEscapes: true,
        defaultParams: true,
        restParams: true,
        forOf: true,
        objectLiteralComputedProperties: true,
        objectLiteralShorthandMethods: true,
        objectLiteralShorthandProperties: true,
        objectLiteralDuplicateProperties: true,
        generators: true,
        spread: true,
        classes: true,
        modules: true,
        jsx: true,
        globalReturn: true
      }
  };
```

Thank you.

**Comment by nzakas** [comment]
Can you explain what's wrong? I can't tell from your screenshot.

**Comment by h13i32maru** [comment]
Sorry, I explain it.

``this is anonymous class.`` is commented on ``export default class``, but the comment is inserted into ``leadingComments`` of ``method1()``.

<img width="486" alt="49c8d898-230e-11e5-8bff-99a130e48cb3" src="https://cloud.githubusercontent.com/assets/985170/8537537/56e2099e-249b-11e5-9060-21f3dc6bddfb.png">



Is this would be the correct behavior?
I expect that the comment is inserted into ``leadingComments`` of ``ExportDefaultDeclaration``.

**Comment by nzakas** [comment]
Thanks for explaining. Yeah, that looks like a bug to me.

**Comment by mysticatea** [comment]
I will try to fix this.

**Comment by nzakas** [comment]
Thanks @mysticatea

**Comment by h13i32maru** [comment]
@mysticatea Thank you :sparkles:
