### ISSUE TITLE
Run tests in chrome

### ISSUE THREAD

**Issue by jasonLaster** [eslint/espree#160]
It'd be great if it were possible to run the tests in the browser. The big win is that chrome devtools would make it easier for newcomers to ramp-up on the project.

I think the big technical hurdle would be loading the tests and fixtures. My naive fix would be to use shelljs to build a static json file that both the node and web runner would consume.

Are there other blockers? I'd be happy to help out.
##

**Comment by nzakas** [comment]
If you're just after devtools, have you tried node-inspector? That's what I use to debug things.

**Comment by jasonLaster** [comment]
That's a good point. 

I'll be working on a karma+mocha setup for esprima (https://github.com/jquery/esprima/issues/1004). Will update the thread when it's in a good spot

**Comment by nzakas** [comment]
Sounds good!

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
