### ISSUE TITLE
Support experimental object spread

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#163]
Object spread is an experimental feature, however, React encourages its use and as such it is one of the most commonly requested features. While this does not mean we will start supporting experimental features, we will make an exception because this keeps coming up as holding back React users from using ESLint out of the box.

The feature should be named `experimentalObjectRestSpread` and allow this syntax:

```
let { ...foo } = bar;
let foo = { a, ...b };
```

Full spec: https://github.com/sebmarkbage/ecmascript-rest-spread

**Comment by xjamundx** [comment]
Love this!

**Comment by nzakas** [comment]
Working on this.

**Comment by bradwestfall** [comment]
What was the result of this? My eslint still complains about `{foo, ...bar}`. Is there a configuration to fix?

**Comment by ilyavolodin** [comment]
@bradwestfall http://eslint.org/docs/user-guide/configuring#specifying-parser-options you are looking for `experimentalObjectRestSpread`

**Comment by bradwestfall** [comment]
Thank you
