### ISSUE TITLE
yield keyword should not be an identifier token

### ISSUE THREAD

**Issue by lo1tuma** [eslint/espree#190]
If I parse the following code:

```js
function *foo() { yield (0) }
```

with `ecmaFeatures: { generators: true }` I get the following token for the `yield` keyword:

```js
{
    type: 'Identifier',
    value: 'yield'
}
```

I would expect the `type` to be `"Keyword"` instead of `"Identifier"`.

**Comment by michaelficarra** [comment]
This cannot be done. You don't know at tokenisation time whether it will be part of an identifier expression or a yield expression or even a binding identifier.

**Comment by lo1tuma** [comment]
If I parse the example from above with esprima I get a token with type `"Keyword"`. But esprima also sets the type to `"Keyword"` for the following code

```js
var yield = foo;
```

**Comment by michaelficarra** [comment]
Yep, and also when it's in expression position and definitely just a regular identifier. So they just chose the other side of the fence.

**Comment by nzakas** [comment]
What are the benefits if we always switch `yield` to be a Keyword instead of Identifier?

**Comment by lo1tuma** [comment]
@nzakas Apart from being compatible with esprima, probably no benefits. Feel free to close this issue.

**Comment by mysticatea** [comment]
I guess this issue can be closed.

```js
"use strict";

const espree = require("espree");
const ast = espree.parse(
    `function *foo() { yield (0) }`,
    {
        ecmaVersion: 6,
        sourceType: "script",
        tokens: true
    }
);

console.log(JSON.stringify(ast, null, 4));
```

```js
...
        },
        {
            "type": "Keyword",
            "value": "yield",
            "start": 18,
            "end": 23
        },
        {
...
```

**Comment by nzakas** [comment]
Yup
