### ISSUE TITLE
espree fails to parse valid ES5 "for (var key = null in obj)"

### ISSUE THREAD

**Issue by mo** [eslint/espree#192]
The code below runs well in Firefox and Chrome but espree fails to parse it. I think it was valid ES5 but perhaps it's no longer allowed in the latest ES standard? It would be useful to at least be able to parse this code, and then tools like eslint can print a warning or not depending on what config flags the user passed (i.e. if it's a legacy or modern code base etc).

var myMap = { "hello": "world" };
for (var x = null in myMap) {
alert(x);
}

**Comment by nzakas** [comment]
It's no longer allowed in ES6, so it was removed (it's hard to keep two slightly different versions of the same thing working). Removing `= null` in your code results in it running the same way.

**Comment by michaelficarra** [comment]
@nzakas That is not necessarily true. If `myMap` has no enumerable properties, the value of `x` outside the loop will be different if the initialiser is removed.

**Comment by nzakas** [comment]
Interesting anecdote.
