### ISSUE TITLE
Report parsing errors explicitly as parsing errors

### ISSUE THREAD

**Issue by IanVS** [eslint/espree#193]
Currently, if Espree bombs out on a parsing error, the error message displayed to the user (at least with `stylish`) is very similar to the errors that are received from linting rules, with the only exception being that a rule name is not provided.  For example:

```js
"use strict";
/*eslint no-delete-var: 2*/

var x;
delete x;
```

Will give:
```js
5:10  error  Delete of an unqualified identifier in strict mode
```

This could cause confusion to new users, who may wonder where the error is coming from, or assume that it is caused by the no-delete-var rule, when in fact it is a parsing error.

I propose one (or both) of the following to add clarity:

* Update formatter(s) to display `parse error` or `fatal error` rather than simply `error` in cases of fatal/parsing errors (https://github.com/eslint/eslint/blob/9dbd9fccfe0473897b22d471eb72f6809eda1bfd/lib/formatters/stylish.js#L50)
* Report the `ruleId` of fatal errors as `parse-error` or `fatal-error`.

Thoughts?

**Comment by nzakas** [comment]
This seems like an ESLint issue, not an Espree issue. Espree can only return parser errors, so there is no ambiguity on this side.

**Comment by IanVS** [comment]
I started off thinking it should be Espree's job to report itself as the `ruleId`, but you're right this should go in ESLint.

**Comment by IanVS** [comment]
Moved to: https://github.com/eslint/eslint/issues/3555
