### ISSUE TITLE
('...') should not parse

### ISSUE THREAD

**Issue by CatWithApple** [eslint/espree#202]
Parsing code 
```javascript
var str1 = ("...");
```
fail with error "Unexpected token )"

**Comment by ilyavolodin** [comment]
What do you expect should happen with the code above?

**Comment by gyandeeps** [comment]
@ilyavolodin Title is misleading but for the above code `espree` throws an exception rather it should parse with no errors.

**Comment by nzakas** [comment]
Interesting, seems like the three dots really confused the parser for some reason.

**Comment by xjamundx** [comment]
Will look into it in a bit if no else figures it out!

**Comment by nzakas** [comment]
Let's hold off until we can switch to Acorn.

**Comment by nzakas** [comment]
Verified this is fixed on master.
