### ISSUE TITLE
Setter with a RestParameter should be a SyntaxError

### ISSUE THREAD

**Issue by mysticatea** [eslint/espree#210]
```js
class A {
    set foo(...value) { }
};
```

Spec:

- http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions
  - `set PropertyName[?Yield] ( PropertySetParameterList ) { FunctionBody }`
  - `PropertySetParameterList : FormalParameter`
  - `FormalParameter` does not include `FunctionRestParameter`.

Related:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1089632

**Comment by nzakas** [comment]
Working on this.

**Comment by nzakas** [comment]
There's a bug in Acorn for this: https://github.com/ternjs/acorn/issues/358

**Comment by nzakas** [comment]
Fixed in 3.0.0.
