### ISSUE TITLE
Parameterized decorators will not be parsed?

### ISSUE THREAD

**Issue by silkentrance** [eslint/espree#211]
See esdoc/esdoc#141

**Comment by ilyavolodin** [comment]
Espree doesn't support experimental features until they are approved. So we currently only support ES6.

**Comment by silkentrance** [comment]
@ilyavolodin thanks for the info, should I leave this open for the future then, when it becomes approved?

**Comment by ilyavolodin** [comment]
It might be a while before it gets approved. We usually reevaluate support for ecma features as they become available. So I'm going to close this for now.
