### ISSUE TITLE
Add ecmaVersion, eliminate most ecmaFeatures

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#222]
We introduced `ecmaFeatures` as a way to start incrementally implementing ECMAScript 6 at a time when it was constantly changing. We did this in order to allow people to start using those features that were ready without forcing usage of all features.

Now that ES6 is finalized and all the features are implemented, most people are using all ES6 features and it's a pain to have to manually configure them all. Additionally, there's no good reason to turn on just some features and not all of them (as that's not how the real world works).

To move forward, we'll be making the following changes:

1. Introduce `ecmaVersion` as the way to indicate which version of ECMAScript you want to target. Possible values will be 3, 5, and 6. This will pass through to Acorn.
1. Remove all ES6 flags from `ecmaFeatures` (`globalReturn`, `jsx`, and experimental features will remain)
1. Remove individual checks for ES6 features (could potentially improve performance).

In all likelihood, going forward we will probably follow a similar pattern of introducing experimental features using `ecmaFeatures` and then rolling them into a larger `ecmaVersion` grouping later on.

**Comment by cletusw** [comment]
> Additionally, there's no good reason to turn on just some features and not all of them (as that's not how the real world works).

@nzakas How do I go about linting for a Node 4 target where only some ES6 features are available? If I leave ecmaVersion at 5, lint will fail even when I use arrow functions, which are supported in Node 4. If I use `ecmaVersion = 6`, developers that locally are using a later version of Node may push code that works for them but fails on our Node 4 build machines. I understand the pain of maintaining all the extra code, but now the pain is on the user to either unnecessarily avoid all ES6 features until the target runtime supports *all* of them, accept build failures, or use Babel (which isn't always an option).

**Comment by platinumazure** [comment]
@cletusw If you're asking in the context of using ESLint, we offer the [no-restricted-syntax](http://eslint.org/docs/rules/no-restricted-syntax) rule to help with this. It's not perfect but it will hopefully be useful to you.

**Comment by cletusw** [comment]
@platinumazure Whoa, that should work great! Thanks! Glad I asked.

**Comment by ilyavolodin** [comment]
@cletusw You can also take a look at this: https://github.com/mysticatea/eslint-plugin-node
