### ISSUE TITLE
eslint-config-eslint breaks the build

### ISSUE THREAD

**Issue by alberto** [eslint/espree#231]
Related to https://github.com/eslint/eslint/issues/4909

**Comment by btmills** [comment]
@alberto what are you seeing? I just pulled `master`, `npm install`, `npm test`, and everything passed. What happens if you `rm -rf node_modules/ && npm i`?

**Comment by alberto** [comment]
Everything passes on my machine too, but it fails on travis. I forgot to link the related espree issue, see https://github.com/eslint/espree/pull/230

**Comment by gyandeeps** [comment]
I expect it too fail as travis is reporting.
Are you guys using node@5?

**Comment by alberto** [comment]
Yes.

**Comment by btmills** [comment]
:hand: I am

**Comment by gyandeeps** [comment]
Thats the reason. try node@4 it will fail on your machine also.
In node@5, it fall back to version of `js-yaml` which is being used by eslint as all the nested dependencies float to the top.

**Comment by alberto** [comment]
It's still green on my machine with node@4.2.4 :/

**Comment by alberto** [comment]
Forget what I just said, I was on the wrong branch, where I had already tried to upgrade eslint and eslint-config-eslint. It fails with node@4.2.4, as it should.

**Comment by alberto** [comment]
Thanks @gyandeeps for solving the mystery!
