### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#24]
We need a nice logo to represent Espree on the interwebs. Any and all help welcome.
##

**Comment by marsmining** [comment]
Here's some variations of the sliced hex. Forgive the literal ideas, I'm not a designer, just like to play.

https://dl.dropboxusercontent.com/u/58390955/espree-hex.pdf

**Comment by EmpireWorld** [comment]
@nzakas I can design a logo for your project. Do you want? (just answer me)

**Comment by nzakas** [comment]
Closing out old issues.
