### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#25]
We need a website to post Espree documentation and a demo. It would be nice if it had the same visual language as the eslint.org, but I don't think that's 100% necessary.
##

**Comment by markphd** [comment]
Did some few changes. Here's some progress..

![Mockup](https://raw.githubusercontent.com/markphd/bearded-guy/gh-pages/content/images/Espree-site.png)

Still more to be done but I'd like to get some feedback from you.

@FredKSchott thanks!

**Comment by nzakas** [comment]
Really like the direction - the colors and typography are great. I even kind of like the logo. The only thing I'm not sure of is the splash image, doesn't quite seem right to me.

**Comment by markphd** [comment]
Is ![this](https://raw.githubusercontent.com/markphd/bearded-guy/gh-pages/content/images/espree-blue-splash.png) better? If you have a particular image in mind or preferred color, please let me know. 
I'm glad that you like the design and I apologize for slow progress, I work 6 days a week and with my work schedule it's hard to buy some time but I'll do my best to produce more for this project. Thanks!

**Comment by markphd** [comment]
I really feel bad for not giving you update, will send one this weekend.

**Comment by nzakas** [comment]
That's okay, you can hold off. We might end up merging back into Esprima so this isn't a high priority at the moment.

**Comment by m1sta** [comment]
If espree continues on it's own it might make sense to highlight the differences to esprima very clearly and early on the homepage.

**Comment by xjamundx** [comment]
Can I build the demo page (similar to http://esprima.org/demo/parse.html)? I find myself needing this all the time and the esprima one is definitely lacking. Do we own espree.org or have a `gh-pages` branch it could live in for now?

**Comment by ilyavolodin** [comment]
If the only thing we want to add for now is espree parser, maybe we should just add it to eslint.org at least until we figure what we want to do with espree in the long run?

**Comment by nzakas** [comment]
Yeah, that makes sense.

**Comment by Announcement** [comment]
Are we still waiting on this or...?
Because if it is, I'll gladly take it! :sunglasses:

**Comment by nzakas** [comment]
@Announcement please feel free!

**Comment by nzakas** [comment]
Closing out old issues.
