### ISSUE TITLE
Uninstallable set of dependencies: 3.1.3

### ISSUE THREAD

**Issue by tractorcow** [eslint/espree#268]
3.1.3 requires:

```
"dependencies": {
  "acorn": "^3.0.4",
  "acorn-jsx": "^2.0.1"
},
```

however, acorn-jsx seems to require the same major version of acorn, so it can't install both acorn 2 and 3 together.

```
npm WARN unmet dependency espree/node_modules/acorn-jsx requires acorn@'^2.0.1' but will load acorn which is version 3.0.4
```

Can you please release 3.1.4 maybe with https://github.com/eslint/espree/commit/c7e5a13b7f3029a1eddf7d7edbba53ec714cb498 fix included?

**Comment by tractorcow** [comment]
I can install fine using `"espree": "https://github.com/eslint/espree.git",` though, for the time being :)

**Comment by tractorcow** [comment]
No, it's a warning; I can live with it for the time being. :) I just am being overly paranoid.

Happy to let you close this issue if you think the warning is safe to ignore. Thanks for the response.

**Comment by nzakas** [comment]
It's definitely safe to ignore.
