### ISSUE TITLE
Support ClassProperty node types

### ISSUE THREAD

**Issue by zxqfox** [eslint/espree#275]
Code
```js
class NotFound {
    prop = 42;
}
```
according to astexplorer isn't parseable and produces `Unexpected token =` error:
http://astexplorer.net/#/7zZPUWPp2k

Guess, we should support this.

**Comment by mysticatea** [comment]
`espree` supports ECMAScript.
In the ECMAScript specification, there is no class property.
Please see: https://tc39.github.io/ecma262/2016/

**Comment by zxqfox** [comment]
Yeah, true. It's a proposal in stage 1: https://github.com/tc39/ecma262#current-proposals

Guess, too early to support this. Thanks.
