### ISSUE TITLE
Support Flow/TypeScript-type annotations

### ISSUE THREAD

**Issue by runn1ng** [eslint/espree#278]
I would love to use Espree (and other tools depending on it) with Flow / TypeScript. (I work with Flow only, but other people like TypeScript and it has a similar syntax.)

There is something for ESLint here - https://github.com/gcazaciuc/eslint-plugin-flowtype - but I want to use Espree directly on the code, and I am not sure how to wire that plugin into that.

**Comment by ilyavolodin** [comment]
Espree supports only stable ECMA Script features. As such, it will not support flow, until (and if) it becomes part of the ECMA spec. You can use `babel-eslint` if you want to lint code with flow. For TypeScript we already have a project started here: https://github.com/eslint/typescript-eslint-parser It's still in pre-alpha state though.

Closing as we are not planning on adding support for flow at this point.

**Comment by xjamundx** [comment]
@runn1ng would something like https://github.com/babel/babylon do what you need? It has flow support
