### ISSUE TITLE
async function and await expression!

### ISSUE THREAD

**Issue by mysticatea** [eslint/espree#287]
> Async functions are now stage 4 and will be included in ES2017!
> https://twitter.com/bterlson/status/758826160700530688

We can support those now!

**Comment by xjamundx** [comment]
I wonder if acorn will do it natively, or if we'll need their plugin?

**Comment by nzakas** [comment]
Yup, waiting to hear back from Acorn. If they don't want to do it yet, then we'll hack it in here.

**Comment by kaicataldo** [comment]
Any progress on this? Could we start by using [this plugin](https://www.npmjs.com/package/acorn-es7-plugin)?

**Comment by mysticatea** [comment]
I'm working on https://github.com/ternjs/acorn/pull/446 😉

**Comment by xjamundx** [comment]
YEAAAAH!

**Comment by kaicataldo** [comment]
Wow, awesome! :tada:

**Comment by benmosher** [comment]
Released a few hours ago, looks like: https://github.com/ternjs/acorn/pull/446#issuecomment-245209683

**Comment by nzakas** [comment]
Cool, if someone wants to put a PR together, we can merge into Espree and it will make it into the next version of ESLint.

**Comment by kaicataldo** [comment]
Cool - I'll try to get to it tonight if someone doesn't beat me to it

**Comment by xjamundx** [comment]
If you can't get to it, I'll be back up :)

**Comment by kaicataldo** [comment]
Unfortunately, didn't end up having as much time as I thought I would tonight - feel free to take it, @xjamundx!

**Comment by nzakas** [comment]
I'll do it.

**Comment by nzakas** [comment]
Ugh, something is really wrong - a bunch of tests are failing with parsing errors. I don't have the energy to investigate but I've pushed the `issue287` branch to the repo if someone else wants to take a look.

**Comment by xjamundx** [comment]
K will try to take a look in a bit, thanks for starting this friends!

**Comment by xjamundx** [comment]
Confirmed 24 errors with the upgrade. Mostly related to the exponential operator.

**Comment by kaicataldo** [comment]
Wonder if it has something to do with [this](https://discuss.ternjs.net/t/acorn-release-4-0-0/67):
>A number of internal method signatures changed, so plugins might need
to be updated.

**Comment by xjamundx** [comment]
Oh n/m I didn't `npm i`. There are actually `96` errors.

**Comment by nzakas** [comment]
Heh, I was just going to say, I got over 90 errors. :)

**Comment by xjamundx** [comment]
I'm looking into this change:
https://github.com/ternjs/acorn/commit/28cbcbc9a6aeb5e6f7b8551d62c1d18d57f2e3b1

This is a pretty common error amongst the 96 (74 instances):
```
     SyntaxError: Unexpected token :
      at Parser.instance.raise.instance.raiseRecoverable (espree.js:9:14226)
      at Parser.instance.unexpected (espree.js:9:15709)
      at Parser.pp$3.parsePropertyValue (node_modules/acorn/dist/acorn.js:2140:12)
      at Parser.instance.parseObj (espree.js:9:13497)
      at Parser.pp$3.parseExprAtom (node_modules/acorn/dist/acorn.js:1930:19)
      at Parser.pp$3.parseExprSubscripts (node_modules/acorn/dist/acorn.js:1817:21)
      at Parser.pp$3.parseMaybeUnary (node_modules/acorn/dist/acorn.js:1794:19)
      at Parser.pp$3.parseExprOps (node_modules/acorn/dist/acorn.js:1736:21)
      at Parser.pp$3.parseMaybeConditional (node_modules/acorn/dist/acorn.js:1719:21)
      at Parser.pp$3.parseMaybeAssign (node_modules/acorn/dist/acorn.js:1696:21)
      at Parser.pp$1.parseExport (node_modules/acorn/dist/acorn.js:1220:23)
      at Parser.pp$1.parseStatement (node_modules/acorn/dist/acorn.js:752:71)
      at Parser.pp$1.parseTopLevel (node_modules/acorn/dist/acorn.js:656:25)
      at Parser.parseTopLevel (espree.js:9:8854)
```

**Comment by xjamundx** [comment]
Okay no progress yet. Back to work for a bit, will revisit later today if I can.

**Comment by xjamundx** [comment]
okay progress. there's a new `isAsync` boolean you have to pass to the `parsePropertyValue` function.

**Comment by xjamundx** [comment]
@nzakas do you mind if I commit directly to your PR or should I just base my thing off it?

**Comment by nzakas** [comment]
Feel free to work directly on my branch

**Comment by xjamundx** [comment]
Okay now there's only 4-5 tests failing. Of course `async` doesn't actually work yet, but it's a start :)

**Comment by xjamundx** [comment]
Current errors are these. Wondering if we can just go along with their new line numbers or if we're doing something wrong... will take a look later tonight.

```

  1) ecmaVersion Scripts with 6/destructuring-and-spread/error-complex-destructured-spread-first should parse correctly when sourceType is script:

      AssertionError: expected { Object (index, lineNumber, ...) } to deeply equal { Object (index, lineNumber, ...) }
      + expected - actual

       {
      -  "column": 6
      -  "index": 5
      +  "column": 5
      +  "index": 4
         "lineNumber": 1
         "message": "Comma is not permitted after the rest element"
       }
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.module.exports.assertMatches (tests/lib/tester.js:61:16)
      at Context.<anonymous> (tests/lib/ecma-version.js:69:24)

  2) ecmaVersion Scripts with 6/destructuring-and-spread/invalid-not-final-array-empty should parse correctly when sourceType is script:

      AssertionError: expected { Object (index, lineNumber, ...) } to deeply equal { Object (index, lineNumber, ...) }
      + expected - actual

       {
      -  "column": 6
      -  "index": 5
      +  "column": 5
      +  "index": 4
         "lineNumber": 1
         "message": "Comma is not permitted after the rest element"
       }
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.module.exports.assertMatches (tests/lib/tester.js:61:16)
      at Context.<anonymous> (tests/lib/ecma-version.js:69:24)

  3) ecmaVersion Scripts with 6/destructuring-and-spread/not-final-array should parse correctly when sourceType is script:

      AssertionError: expected { Object (index, lineNumber, ...) } to deeply equal { Object (index, lineNumber, ...) }
      + expected - actual

       {
      -  "column": 6
      -  "index": 5
      +  "column": 5
      +  "index": 4
         "lineNumber": 1
         "message": "Comma is not permitted after the rest element"
       }
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.module.exports.assertMatches (tests/lib/tester.js:61:16)
      at Context.<anonymous> (tests/lib/ecma-version.js:69:24)

  4) ecmaVersion Modules with 6/destructuring-and-spread/error-complex-destructured-spread-first should parse correctly when sourceType is module:

      AssertionError: expected { Object (index, lineNumber, ...) } to deeply equal { Object (index, lineNumber, ...) }
      + expected - actual

       {
      -  "column": 6
      -  "index": 5
      +  "column": 5
      +  "index": 4
         "lineNumber": 1
         "message": "Comma is not permitted after the rest element"
       }
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.module.exports.assertMatches (tests/lib/tester.js:61:16)
      at Context.<anonymous> (tests/lib/ecma-version.js:94:24)

  5) ecmaVersion Modules with 6/destructuring-and-spread/invalid-not-final-array-empty should parse correctly when sourceType is module:

      AssertionError: expected { Object (index, lineNumber, ...) } to deeply equal { Object (index, lineNumber, ...) }
      + expected - actual

       {
      -  "column": 6
      -  "index": 5
      +  "column": 5
      +  "index": 4
         "lineNumber": 1
         "message": "Comma is not permitted after the rest element"
       }
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.module.exports.assertMatches (tests/lib/tester.js:61:16)
      at Context.<anonymous> (tests/lib/ecma-version.js:94:24)

  6) ecmaVersion Modules with 6/destructuring-and-spread/not-final-array should parse correctly when sourceType is module:

      AssertionError: expected { Object (index, lineNumber, ...) } to deeply equal { Object (index, lineNumber, ...) }
      + expected - actual

       {
      -  "column": 6
      -  "index": 5
      +  "column": 5
      +  "index": 4
         "lineNumber": 1
         "message": "Comma is not permitted after the rest element"
       }
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.module.exports.assertMatches (tests/lib/tester.js:61:16)
      at Context.<anonymous> (tests/lib/ecma-version.js:94:24)
```

**Comment by nzakas** [comment]
We should see if the new locations are more accurate than the old. If not, maybe there's an Acorn bug.

**Comment by xjamundx** [comment]
I'm pretty sure the new numbers are more accurate.

**Comment by xjamundx** [comment]
Started adding tests and a basic implementation. Most of the tests aren't working yet and I need to be done for the night, so anyone can take over if they want or I'll try to take it back tommorow :)

**Comment by mysticatea** [comment]
Thank you, everyone.

For reference, there are many test cases in [acorn/test/tests-asyncawait.js](https://github.com/ternjs/acorn/blob/master/test/tests-asyncawait.js) and [acorn/test/tests-trailing-commas-in-func.js](https://github.com/ternjs/acorn/blob/master/test/tests-trailing-commas-in-func.js)

**Comment by xjamundx** [comment]
Great thanks @mysticatea we'll use those test cases!

**Comment by xjamundx** [comment]
Still working on creating those tests. I remember there was some easy way to generate the tests, but I can't remember how.

**Comment by xjamundx** [comment]
K continuing this work today...

**Comment by nzakas** [comment]
Looks like my comment didn't go through :-/ Look at `tools/create-tests.js`

**Comment by xjamundx** [comment]
`tools/create-tests.js` is working great, mainly having an issue with coming up for names for all 100+ tests I'm copying over from acorn :) Hope to have all of the test files generated by this afternoon, though not all of the cases are fully working.

**Comment by xjamundx** [comment]
In case it needs to be used later, I'm going to paste in my test cases.

**Comment by xjamundx** [comment]
Updated the branch with fairly working code, realized I need to update the `create-test.js` to include `ecmaVersion: 8`, so running it again and hopefully won't get 200 errors :)

**Comment by xjamundx** [comment]
Issue appears to be that the newly generated nodes are missing `start` and `end` properties in some cases. Probably doing something silly.

**Comment by nzakas** [comment]
I'm not sure if this is the issue, but in the test fixtures we don't include `start` and `end`, and the output from Espree is normalized to skip those in the tests.

**Comment by xjamundx** [comment]
@nzakas cool that makes sense I made some minor modifications to `create-test`, so maybe I turned them back on. I'm hoping I'll get this fixed pretty soon. It's going well-ish :)

**Comment by xjamundx** [comment]
@nzakas it seems like `create-test` is adding `start` and `end`. Is that something I did wrong specifically in the implementation of async/await or do i just need to manually remove them?

**Comment by xjamundx** [comment]
added this thing to `create-test` and now more things are passing:
```
 recursivelyRemoveStartAndEnd(result)
    function recursivelyRemoveStartAndEnd(o) {
        if (Array.isArray(o)) {
            o.forEach(recursivelyRemoveStartAndEnd)
        } else if (o && typeof o === 'object') {
            delete o.start
            delete o.end
            Object.keys(o).filter(key => key !== 'loc').forEach((key) => {
                recursivelyRemoveStartAndEnd(o[key])
            })
        }
    }
```

i'm obviously doing something wrong :-p

**Comment by xjamundx** [comment]
Once this was fixed new issues revolve around the `await` identifier being banned in strict mode. Need to tweak how we put tests for strict/module mode. I'm soooo rusty, but I think I'll get it.

**Comment by nzakas** [comment]
@xjamundx Espree outputs `start` and `end` by default, it comes from Acorn and is hard to remove. So `create-test.js` is just using the raw output from Espree. You can use this to easily strip stuff you don't want in the output:
https://github.com/eslint/espree/blob/master/tests/lib/tester.js#L26

**Comment by xjamundx** [comment]
Thanks @nzakas !

**Comment by xjamundx** [comment]
Found what I need. Filename magic :)
```
var scriptOnlyTestFiles = allTestFiles.filter(function(filename) {
    return filename.indexOf("modules") === -1;
});

var moduleTestFiles = allTestFiles.filter(function(filename) {
    return filename.indexOf("not-strict") === -1 && filename.indexOf("edge-cases") === -1;
});
```

**Comment by xjamundx** [comment]
Got all tests to pass. Updating now. Probably some additional tests may be needed, but it's getting close hopefully!

**Comment by xjamundx** [comment]
Let me open a PR

**Comment by xjamundx** [comment]
**Note to self:**
next time don't try to add so many tests :-p
