### ISSUE TITLE
`sourceType: "module"` with ES5 target?

### ISSUE THREAD

**Issue by isiahmeadows** [eslint/espree#289]
It'd be helpful with Rollup, if you don't want to use Babel.

**Comment by isiahmeadows** [comment]
Related to ternjs/acorn#459. I filed it in both places because it's an Acorn issue that will also need support here (`sourceType: "module"` overrides `ecmaVersion: 5` when it IMO shouldn't).

**Comment by nzakas** [comment]
I'm sorry, this just isn't technically possible. You can't have ES6 modules with ES5.
