### ISSUE TITLE
`async` is not a reserved word

### ISSUE THREAD

**Issue by feross** [eslint/espree#296]
ESLint gives me `Parsing error: Unexpected token :` on this line:

```js
suite.run({ async: true })
```

Is `async` actually a reserved word? It doesn't appear so: https://tc39.github.io/ecma262/#sec-keywords

**Comment by platinumazure** [comment]
This has been fixed in master, I believe.

**Comment by feross** [comment]
Right you are: https://github.com/eslint/espree/pull/295
