### ISSUE TITLE
Attach browserified binaries to releases

### ISSUE THREAD

**Issue by Hirse** [eslint/espree#306]
When drafting a new release could you add the browserified file to the release on GitHub?
I was unable to find the browser version as download, so I think it would be a valuable addition.

**Comment by nzakas** [comment]
@Hirse Espree isn't really designed to be used in a browser, so I wouldn't want to try to encourage that with a browserified version in the package.

**Comment by Hirse** [comment]
@nzakas I didn't mean to add it to the package, but to attach it here: https://github.com/eslint/espree/releases.

**Comment by nzakas** [comment]
Understood. This is still something we don't want to support. Espree is intended to run only in Node at this point.
