### ISSUE TITLE
Template token objects differ from other token objects

### ISSUE THREAD

**Issue by iancmyers** [eslint/espree#319]
While fixing an issue in `eslint-plugin-react` (https://github.com/yannickcr/eslint-plugin-react/issues/1061), I noticed that template tokens differ from other tokens. A typical token looks like this:

```
Token {
  type: 'String',
  value: '"bar"',
  start: 44,
  end: 49,
  loc:
   SourceLocation {
     start: Position { line: 4, column: 11 },
     end: Position { line: 4, column: 16 } },
  range: [ 44, 49 ] }
```

A template token looks like this:

```
{ type: 'Template',
  value: '`bar`',
  loc:
   { start: Position { line: 4, column: 11 },
     end: Position { line: 4, column: 16 } },
  range: [ 44, 49 ] }
```

I've not be able to figure out why templates are plain JavaScript objects and not of the class type `Token` (aside from the fact that the [template tokens are constructed differently in the token translator](https://github.com/eslint/espree/blob/58f75be6b89d8904b6366ed368045cb02c4a4e33/lib/token-translator.js#L43)). 

The more pressing issue, in my mind, is the omission of `start` and `end` properties at the top level of the template token object. The issue cited above was caused by passing `token.start` into eslint's `getNodeByRangeIndex` method. I fixed the issue by using `range[0]` (https://github.com/yannickcr/eslint-plugin-react/pull/1077), however I fear that other downstream projects are relying on tokens have a consistent object construction and always having `start` and `end`.

It seems like the quick-fix would be to copy the `range` values into `start` and `end` properties on the template tokens. If that would be sufficient for now, I'd be happy to PR that.

**Comment by nzakas** [comment]
That seems like a reasonable fix for what appears to be an obvious bug. Probably just an oversight as we went back and forth on whether or not start and end should end up on the nodes. I'd still recommend using range in rules, as that is supported by all parsers whereas start and end are just Acorn leftovers in Espree.

**Comment by kaicataldo** [comment]
@iancmyers Sorry for losing track of this. Is this still something you'd be willing to make a PR for?

**Comment by iancmyers** [comment]
Yep! Incoming soon.
