### ISSUE TITLE
Does Espree has any built-in Ast Walker?

### ISSUE THREAD

**Issue by EmpireWorld** [eslint/espree#324]
Does Espree has any built-in Ast Walker?
If doesn't have please suggest one.

Thanks.
Kind Regards.

**Comment by ilyavolodin** [comment]
@EmpireWorld espree doesn't come with ast walker, however, you can use estraverse (https://github.com/estools/estraverse) which is a module used by ESLint.

**Comment by EmpireWorld** [comment]
@ilyavolodin Thanks. i will use that. i wish you be happy.
