### ISSUE TITLE
Support test fixtures for when feature = false does not result in an error

### ISSUE THREAD

**Issue by FredKSchott** [eslint/espree#33]
For Unicode code point escapes, the string values are still valid JavaScript regardless of the feature state. But the test runner is hard-coded to check for a thrown error if the features is set to off. Thus, I'm unable to write passing tests for this feature.

A few ideas:
1. Add an option to *.config.js to skip this second test
2. Remove the test entirely, since I'm not sure how valuable it is to us (checking that new features aren't backwards compatible).

@nzakas thoughts?

**Comment by nzakas** [comment]
Unicode code point escapes should throw an error in ES5 environments, so the year runner is forcing you to make it so. :)

You can try it out for yourself in Node.

**Comment by FredKSchott** [comment]
Ahhh I see whats going on now, the escaped backslashes were messing with my. Guess this proves exactly why we should keep them :)
