### ISSUE TITLE
Node Scope

### ISSUE THREAD

**Issue by EmpireWorld** [eslint/espree#333]
How can i get node scope? (global, function or ...)

**Comment by not-an-aardvark** [comment]
I think "function", but I can't be sure because your question is a bit vague.

**Comment by EmpireWorld** [comment]
How can i get the node scope?

Like the below:
```javascript
// It should have "global" scope.
const exampleConst = "";
class Example {
    constructor(config) {
        // It should have "instance" scope.
        this.config = config;
    }
}

// It should have "static" scope
module.exports
```

**Comment by not-an-aardvark** [comment]
It's still not clear what you're asking. Could you clarify the behavior that you're looking for? I don't understand what you mean by "instance", "static", or "global" scope in this context.

You can use [eslint-scope](https://github.com/eslint/eslint-scope) to run scope analysis on an AST, but it doesn't have things like "instance" or "static" scope.

**Comment by EmpireWorld** [comment]
I'm writting a documentation generator so i need to know the node scope.

Each node sits in some where of you files.

It can be inside of a function or class.

When a variable declared inside of a class it must have "instance" scope.

When a variable declared in the global scope it must have a "global" scope.

Sometimes special variables like `module.exports` must have "static" scope.

Also when a variable declared inside of a function must have "inner" scope.

Do you understand? How can i get these scopes from espree nodes?

**Comment by not-an-aardvark** [comment]
Thanks for clarifying, I think that makes sense. Espree doesn't provide this information directly, so you would need to determine this scoping info yourself. After parsing source code with Espree you can use something like [estraverse](https://github.com/estools/estraverse) to traverse the AST. Then you can mark the scope of given nodes however you want based on your documentation generator's scoping rules.

**Comment by EmpireWorld** [comment]
Thanks for fast reply.
Best wishes for you and your team.

**Comment by EmpireWorld** [comment]
@not-an-aardvark How can i detect the scope using estraverse?

**Comment by not-an-aardvark** [comment]
I'm not sure; one way to do it would be to use estraverse to traverse the AST, and then store scope information on a node-specific basis based on the types of nodes you encounter. For example, if the traversal encounters a `MethodDefinition` node, you could mark all child references as "instance" scope.

You're trying to implement some custom behavior which isn't supported directly by estraverse or espree, so a lot of the details will depend on your own code. I can help you with any questions you have relating to espree or estraverse, but I might not be able to help you with questions that are specific to your implementation.

**Comment by EmpireWorld** [comment]
@not-an-aardvark Thanks for the respond.
