### ISSUE TITLE
Add option to specify my own acorn

### ISSUE THREAD

**Issue by touzoku** [eslint/espree#334]
Acorn and acorn-jsx are hardcoded in espree which makes it hard to extend espree for other syntax flavors.
```javascript
// reference code from espree
var acornJSX = require("acorn-jsx/inject"),
var rawAcorn = require("acorn");
var acorn = acornJSX(rawAcorn);

// following down the code
        if (extra.ecmaFeatures.jsx) {
            // Should process jsx plugin before espree plugin.
            acornOptions.plugins = {
                jsx: true,
                espree: true
            };
        }
```

I wrote my own acorn extension, and I would like to feed it to espree in my eslint plugin.

The way I do it now is monkey patch api.verify in eslint with the following code:
```javascript
const proxyquire = require('proxyquire');

let espreePath = Object.keys(requireCache).find(key => key.endsWith(path.join('espree', 'espree.js')))
espreePath = espreePath ? espreePath : 'espree'
let acornPath = Object.keys(requireCache).find(key => key.endsWith(path.join('dist', 'acorn.js')))
acornPath = acornPath ? acornPath : 'acorn'

const acorn = require(acornPath)
const acornVFEL = require('@salesforce/acorn-visualforce/dist/inject')(acorn, true)
const espree = proxyquire(espreePath, { acorn: acornVFEL })
```

Which is a) ugly, b) prone to errors.

The problem with this approach is that acorn-jsx is injected later overriding my overrides to acorn. Ideally, my plugin should be injected after acorn-jsx, but there is no way I can do it currently.

Is it possible to add an option to espree to specify my own acorn package in a fashion that acorn-jsx does? It should be a very simple addition, something like `var acorn = options.acorn || require("acorn-jsx")`

**Comment by ilyavolodin** [comment]
I'm not sure this would be the right way to solve this problem. ESLint allows you to change parsers directly. So if your goal is to use your own extension, best way to do that would be to create your own wrapper around Acorn and tell ESLint to use that.

**Comment by touzoku** [comment]
I thought of forking espree just to feed my own acorn extension, but that's the only change I need. Would be a meaningless fork for just one line of code.

I agree, adding such option to espree is not a beautiful solution. In fact, it should be refactored completely to allow injection of its functionality similarly to acorn-jsx. But that's a lot of work I must say, given that the parse and tokenizer functions are both wrapped.

I would really like to have the change above as an interim solution. Or at least change the way you import acorn from injecting acorn-jsx to a plain `var acorn = require('acorn-jsx')` so I can monkey patch it

**Comment by ilyavolodin** [comment]
Sorry, I'm not familiar enough with Espree to make a call. @mysticatea @kaicataldo @not-an-aardvark ideas?

**Comment by not-an-aardvark** [comment]
It seems like it would be nice to do this, but I'm not sure an `acorn` option is the right solution. How difficult would it be to expose Acorn's plugin API in the same way that Acorn exposes it (implemented by just passing everything through to Acorn)? Then we could make things composable -- for example, people could add espree semantics to acorn extensions by just replacing `require('acorn')` in a plugin with `require('espree')`.

**Comment by touzoku** [comment]
@not-an-aardvark `acorn` plugin model is basically functional inheritance, i.e. you wrap the original function with your extension implementing new logic, and for the existing logic you call the original function itself.

Some parts of `espree` functionality can be easily refactored to that approach, because they follow the convention. Basically, everything up until [line 511](https://github.com/eslint/espree/blob/master/espree.js#L511) could be moved in a new `inject.js` file similarly to [acorn-jsx](https://github.com/RReverser/acorn-jsx/blob/master/inject.js) or my plugin [acorn-visualforce](https://github.com/forcedotcom/acorn-visualforce/blob/master/src/inject.js). But the two main functions: parse and tokenize are not compatible with the original `acorn` plugin model.

It would require some effort to rewrite them to make it "injectable", but I'm willing to do this, as long as I'll have confidence that the maintainers are onboard with this change.

**Comment by not-an-aardvark** [comment]
Thanks for explaining. 

> It would require some effort to rewrite them to make it "injectable", but I'm willing to do this, as long as I'll have confidence that the maintainers are onboard with this change.

Please don't do this yet -- I was just throwing an idea out there, and I'm not sure it's the right choice 😃

**Comment by kaicataldo** [comment]
My biggest concern with exposing acorn is that it will make it a lot more difficult should we decide to switch to a different underlying parser in the future. There aren't any plans to do so now, but I think it would be wise to keep that tucked away as an implementation detail and leave us free to make that change should we ever deem it necessary.

**Comment by touzoku** [comment]
@kaicataldo with all respect, `espree`'s code is a 100% acorn-specific. If you decide to move on to another parser, you'd have to at least bump the major version as I presume there will be a lot of other breaking changes (that may include removing an option for `acorn`). I would even change the name of the project, if it was decided to move away from `acorn`.

But adding the configuration option aside, would you be onboard with making `espree` a proper `acorn` plugin instead of a wrapper?

**Comment by ilyavolodin** [comment]
@touzoku Not saying that you are not right, but we already done that once before. Originally Espree was a fork of Esprima. We switch to Acorn when development of Esprima stalled for a bit. While it wasn't a small undertaking, there were no real breaking changes in the end (or they were very limited).

**Comment by kaicataldo** [comment]
@touzoku Not sure I agree that since, as @ilyavolodin mentioned, it's been done before. Re: making Espree an Acorn plugin: what are you envisioning?

**Comment by touzoku** [comment]
@kaicataldo basically, espree.js should be like
```javascript
// using ES6 syntax for brevity
module.exports = {
    ...acorn,
    {plugins: { ...acorn.plugins, espree } },
    Syntax,
    VisitorKeys,
    version,
    tokenize
}
```
where `espree` is the anonymous function from the line 276.

This is a super-easy change except the `parse` function since it exists in both espree and original acorn.

I suggest decomposing different parts of `parse` to other acorn functions, for example, the translation of `extra.ecmaFeatures` to `acornOptions` could be done in the `loadPlugins` function of acorn instead of the wrapper of `parse`.

Other things like `program.comments = extra.comments` or `program.tokens = extra.tokens` could be moved to an extension of `acorn.Parser.prototype.parseTopLevel` and so on and so forth.

This way espree will expose acorn as is with all necessary extensions to make eslint work

**Comment by kaicataldo** [comment]
Apologies for this falling through the cracks. Thanks for explaining your proposal. @eslint/eslint-team Thoughts?

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
