### ISSUE TITLE
How to get node long name?

### ISSUE THREAD

**Issue by EmpireWorld** [eslint/espree#335]
How can i get node long name?
See the example below:
Here is source code that espree want to parse:
```javascript
class Example {
    sayHello() {
        console.log("Hello! How are you?");
    }
}

function sayImFine() {
    console.log("I'm Fine, Thanks!");
}
```
Here is the `espree.parse()` result: (using estraverse)
```
Node {
    ...
    type: "ClassExpression",
    name: "Example" // Exported from `id` (manually)
}
Node {
    ...
    type: "MemberExpression"
    name: "sayHello" // Here i need `Example.sayHello` How do i do it?
}
Node {
    ...
    type: "FunctionDeclaration",
    name: "sayImFine" // Here i need `global.sayImFine`
}
```
How do i do it?

**Comment by kaicataldo** [comment]
Apologies for the delay in responding. I'm not entirely sure what the question is - ESLint uses [estraverse](https://github.com/estools/estraverse) for AST traversal, which might be helpful?

**Comment by EmpireWorld** [comment]
I mean i want to get the long name, like this example:
```javascript
Node {
    ...
    type: "MemberExpression"
    name: "sayHello" // Here i need `Example.sayHello` How do i do it?
}
```

The long name should be: `Example.sayHello`.

The format is look like this: `namespace.(method or property name)`

How can i achieve this?

Thanks.

**Comment by not-an-aardvark** [comment]
If you still have the string that you originally parsed, you can use `string.slice(node.range[0], node.range[1])` to get the source text for a node.

**Comment by EmpireWorld** [comment]
Does `node.range` exists in all ASTs? such as Babel ast.

Because currently i am using babylon and babel-traverse.

Thanks.

**Comment by not-an-aardvark** [comment]
I think some parsers produce `node.start` and `node.end` rather than `node.range[0]` and `node.range[1]`. Espree happens to produce both.

**Comment by EmpireWorld** [comment]
You are right but that is a number:

This is a babylon ast node:
```javascript
Node {
  type: 'StringLiteral',
  start: 302,
  end: 308,
  loc: 
   SourceLocation {
     start: Position { line: 13, column: 39 },
     end: Position { line: 13, column: 45 } },
  extra: { rawValue: 'utf8', raw: '\'utf8\'' },
  value: 'utf8' }
```

What should i do with the numbers?

**Comment by not-an-aardvark** [comment]
If you have the original string that you parsed, you can use `string.slice(node.start, node.end)`.

**Comment by EmpireWorld** [comment]
Yes. right, but it returns the same value as the Identifier name. i need long name.

**Comment by not-an-aardvark** [comment]
If `node` is the `MemberExpression` node, then `string.slice(node.start, node.end)` will return the full text of the node.

I'd like to help you solve your problem, but it's going to difficult to help unless you give more information. If you're still having trouble, it would be useful if you could provide an example of the code that you're using.

**Comment by EmpireWorld** [comment]
This is my example script that i was used:

```javascript
const path = require('path');
const fs = require('fs');

let resolvedPath = path.resolve(process.argv[2], process.argv[3]);
fs.readFile(resolvedPath, 'utf8', (err, data) => {
  if (err) {
    throw err;
  }
  console.log('Data:', data);
});

function getInfo() {
  return fs.readFileSync(resolvedPath, 'utf8');
}

/**
 * Example Class makes an Simple API for manipulating sample data.
 *
 * @class
 */
class ExampleClass {

  doSample() {

  }

}
```

Currently i want to get the `doSample` long name. `ExampleClass#doSample`

Thanks.

**Comment by not-an-aardvark** [comment]
I see. You will have to create that yourself by traversing the AST and concatenating strings -- espree does not provide a way to do that.

**Comment by EmpireWorld** [comment]
Thanks for your notice. i will do it myself.
