### ISSUE TITLE
Simplify code by using acorn-object-rest-spread

### ISSUE THREAD

**Issue by ehmicky** [eslint/espree#337]
Joining forces with [https://github.com/victor-homyakov/acorn-object-rest-spread](https://github.com/victor-homyakov/acorn-object-rest-spread) and replacing `experimentalObjectRestSpread` with this acorn plugin would remove substantial parts of the current code base, and produce the same output.

Note: I only intent to report this issue, not submit a PR.

**Comment by not-an-aardvark** [comment]
No, I don't think so.

**Comment by platinumazure** [comment]
Closing as it seems this is no longer necessary. @ehmicky Thanks for the issue and please feel free to comment here (or open a new issue) if you feel we are missing something here.
