### ISSUE TITLE
Using Object shorthand with a prop named "async" results in a parse error

### ISSUE THREAD

**Issue by muffinresearch** [eslint/espree#340]
Here's a reduced test case that generates the error: 

```javascript
/* global console */

const async = false;
const bar = 1;
const foo = { async, bar };

console.log(foo);
```
Error message is: error  Parsing error: Unexpected token ,

Eslint version is: v4.0.0-rc.0
espree: 3.4.3

Using ecmaversion 8.

Changing: `const foo = { async, bar };` to `const foo = { async: async, bar };` prevents the error.

Relates to #295

**Comment by mysticatea** [comment]
Thank you for the report.

I confirmed it.
Acorn, the upstream parser of espree, also has the problem.
Additionally, espree overrides the problem method, so we have to fix espree as well.

**Comment by ilyavolodin** [comment]
Does acorn even support object spread out of the box? It's still an experimental feature.

**Comment by not-an-aardvark** [comment]
It seems like the issue is with object shorthand, not object spreading.
