### ISSUE TITLE
Enhancement Proposal: dynamic imports

### ISSUE THREAD

**Issue by kaicataldo** [eslint/espree#344]
Now that dynamic imports are now stage 3 and are used by Webpack v2 for code splitting, I'd like to propose we add support for this in Espree/ESLint behind an option like `experimentalDynamicImport: true`.

An Acorn plugin already exists, and it looks like it's well used: https://www.npmjs.com/package/acorn-dynamic-import

**Comment by kaicataldo** [comment]
For reference, at my place of work, we're using `babel-eslint` just for dynamic imports right now.

**Comment by mysticatea** [comment]
My state is negative about supporting stage 3. There are some reasons.

- there is a precedent that a stage 3 proposal dropped; simd
- after we implemented rest spread properties, AST of the syntax changed without compatibility. Now, there are 3 kinds of AST; espree's, babel-eslint's, and ESTree's. It's confusing.
- stage 3 is unstable. Chrome beta enables rest properties by default, but the syntax has been changed in the last 39th meeting. Chrome's syntax is now non-standard.
- babel-eslint is supporting experimental syntax.

**Comment by kaicataldo** [comment]
@mysticatea In general, I agree. This feels like a special case to me because of Webpack. Personally, I think it doesn't feel great to have to use another parser to get code splitting in such a ubiquitous tool.

**Comment by mysticatea** [comment]
Doesn't webpack support `require`?

**Comment by kaicataldo** [comment]
Yeah, it's also possible to use `require.ensure()` instead of `import()`. I suppose that's a fair argument.

**Comment by soda0289** [comment]
Would it be possible to make espree an acorn plugin? Then you could just use acorn with eslint and use any plugin you wanted.

**Comment by kaicataldo** [comment]
@soda0289 Relevant discussion: https://github.com/eslint/espree/issues/334

**Comment by nzakas** [comment]
Also :-1:  Our position has always been that using experimental features requires using Babel. Babel does a really good job at supporting them, and as long as Babel-ESLint exists, I don't think we should change our policy on this.

**Comment by kaicataldo** [comment]
With 2 👎s from TSC members, in going to close this.

**Comment by tschaub** [comment]
Should a new issue be opened now that dynamic imports are at Stage 4 (https://github.com/tc39/proposal-dynamic-import/pull/78)?

**Comment by mdjermanovic** [comment]
@tschaub espree supports dynamic imports since v6.1.0, if the [`ecmaVersion`](https://github.com/eslint/espree#options) is set to 2020 or higher.

Ref https://github.com/eslint/espree/pull/415

**Comment by tschaub** [comment]
Thanks, @mdjermanovic.

Different subject, but I’m curious if there is discussion somewhere about why the default for `ecmaVersion` is kept so low.

**Comment by kaicataldo** [comment]
@tschaub It's been discussed many times in the eslint/eslint repo (and we've had proponents both for keeping `ecmaVersion` as it is currently and setting to latest), but the summary is that we've erred on the safer side of things by making new syntax opt-in rather than opt-out. This means that someone running their code in an environment that doesn't support the latest syntax would never accidentally push code that couldn't execute to production.
