### ISSUE TITLE
Is possible to convert ast node back to string ?

### ISSUE THREAD

**Issue by jasdevsidhu12** [eslint/espree#351]
Hi Developers,

I'm just amaze with this espree project and I wanted to inquire on a thing. 
I was looking through the project and I can't find any docs on converting back ast to string. I also look at the "espree" and "ast" object properties but I can't find any. Is it possible in the first place ? Is there a way to convert it back?.

Thanks and sorry for the trouble and marking this as an issue.

**Comment by btmills** [comment]
@jasdevsidhu12 thanks for the kind words! The answer depends on what you want to do:

- To convert an arbitrary AST to source code, you'll need a code generator - something like [estools/escodegen](https://github.com/estools/escodegen). A code generator typically does not preserve formatting, though some do their best ([benjamn/recast](https://github.com/benjamn/recast) being one example).
- If you want to get the original source code for a parsed AST node, you'll need access to the original source code as a string, and then you can use the node's `range` property to pull a substring from the original source code.

**Comment by jasdevsidhu12** [comment]
thanks @btmills , I will give it go
