### ISSUE TITLE
async shorthand functions cause parsing errors if they are named 'delete' or 'import' 

### ISSUE THREAD

**Issue by Standard8** [eslint/espree#352]
Using ESLint, with Espree 3.5.0, we are seeing failures that we were not seeing with 3.4.3.

Example failure:
```js
var foo = {
  async import() {
  }
}
```

With 3.5.0 this fails with `Parsing error: Unexpected token import`

Downgrading to 3.4.3 or changing the name of the function to something else, e.g. `bar` passes.

We've also seen that `async delete() {}` causes a similar issue.

I suspect this is a regression from #341 given the release notes.

**Comment by mysticatea** [comment]
Thank you for this issue.

This has been fixed already on the master branch of upstream: https://github.com/ternjs/acorn/issues/584.
Please wait for the next patch release of acorn, then re-install it.

**Comment by Standard8** [comment]
Unfortunately updating acorn isn't enough as espree seems to be overriding this issue. I've just created #353 with the fix ported across.

**Comment by mysticatea** [comment]
Oops, I'm sorry, I had forgotten that.

**Comment by not-an-aardvark** [comment]
Closed in https://github.com/eslint/espree/commit/5eb1388809c789e50cdb56bf90192f0df36a3987

**Comment by Standard8** [comment]
I'm just wondering if there is a likely ETA for when the fix for this could be included in a release?

Currently I'm trying to resolve a few issues with dependencies in one of the modules I'm working on for Firefox, but I'm hitting up against this issue at the moment. Having an ETA would be useful for knowing when I can get back to fixing it.

Thanks.

**Comment by not-an-aardvark** [comment]
We had been planning to release it along with the scheduled [ESLint release](https://github.com/eslint/eslint/issues/9220) next week.

**Comment by Standard8** [comment]
@not-an-aardvark Next week is fine, it'll be good timing for us.
