### ISSUE TITLE
Parsing error when yielding JSX without parenthesis

### ISSUE THREAD

**Issue by kentor** [eslint/espree#355]
Example:

```js
function* test() {
  yield <Hey />;
}
```

https://astexplorer.net/#/gist/a96aa934d341355b14576ef0e006b02a/97e8c8019fd5610b88d9403b61406707188d8d1c

However, if you use the babylon7 parser it works.

I used to just add parens around the JSX for this to work: 

```js
function* test() {
  yield (<Hey />);
}
```

But it is now an issue when using eslint-plugin-prettier because prettier removes the parens and then eslint gets a parsing error after that.

**Comment by not-an-aardvark** [comment]
Thanks for the report. It looks like this issue is caused by [acorn-jsx](https://github.com/RReverser/acorn-jsx), so I would recommend reporting an issue there instead.
