### ISSUE TITLE
Identical AST for imports with and without a clause

### ISSUE THREAD

**Issue by JamesHenry** [eslint/espree#357]
Please see https://github.com/eslint/typescript-eslint-parser/issues/329

Babylon and TypeScript differentiate between them in their respective ASTs, but many other parsers, including espree do not.

Here is babylon: http://astexplorer.net/#/gist/c94eb5f0c20528d75fbf93f7f66e4bed/c85dfaa00006f2cea37013973925b6fd253eb070

It uses `importKind: 'value'` for the first (with the `{}`) but not the second.

Do we think something similar in espree would make sense?

**Comment by mysticatea** [comment]
Personally, those two syntaxes are not different in semantics, it imports the file and does not bind any item from the file, so I feel reasonable that those are the same AST. It's similar to the fact that `(1 + 2) + 3` and `1 + 2 + 3` are the same AST. If I have misunderstood and those syntaxes have different semantics, those should be different AST.

Anyway, it's a spec issue, so I think that the best place to discuss is the `estree` repo.

**Comment by JamesHenry** [comment]
Interesting, I could not have said that their semantics were identical off the top of my head, but I can also not think of any way in which they are different either... I like the comparison with the arithmetic there.

I will try and track down the relevant discussion from when this was implemented in babylon to see if there is anything we are missing.

**Comment by JamesHenry** [comment]
I will not have time for this for a while I don't think, I will close the issue to make that clear. Thanks @kaicataldo!
