### ISSUE TITLE
Broken parens on return statement

### ISSUE THREAD

**Issue by retrohacker** [eslint/espree#373]
# Repro

espree strips parenthesis from return statements, changing the behavior of the code. This breaks ast serialization/deserialization for react [here](https://github.com/facebook/fbjs/blob/c69904a511b900266935168223063dd8772dfc40/packages/fbjs/src/core/createArrayFromMixed.js#L85-L107).

```js
var espree = require('espree');
var escodegen = require('escodegen');

var file = `
console.log((function () {
    return (
        // I am a comment
        'hello world' +
        // I am another comment
        'this is a test'
    );
})());
`;

var ast = espree.parse(file,
    {
        ecmaVersion: 9,
        sourceType: 'module',
        attachComment: true,
        loc: true,
        range: true,
        ecmaFeatures: {
            jsx: true,
            globalReturn: true,
            impliedStrict: false,
        }
    });

console.log(escodegen.generate(ast, { comment: true }));
```

# Output

### original

```js
console.log((function () {
    return (
        // I am a comment
        'hello world' +
        // I am another comment
        'this is a test'
    );
})());
```

```text
hello worldthis is a test
```

### generated

```js
console.log(function () {
    return // I am a comment
    'hello world' + // I am another comment
    'this is a test';
}());
```

```text
undefined
```

May be related to the escodegen bug here: https://github.com/estools/escodegen/issues/365

espree handles this a bit more gracefully, putting the return value on the same line but still stripping the parens. The repro case on the escodegen issue actually works fine with espree but, when you add comments between lines in the parens, espree breaks the return statement. This also breaks serializing/deserializing react in the same way.

---

### updates

* Originally included the wrong repro case, updated to match output

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. This seems like a potential bug in `escodegen`, but I don't think this is an issue with espree, because ASTs never include information about parentheses.

**Comment by retrohacker** [comment]
If an AST doesn't include information about parenthesis, how would a code generator know to insert them?

(sorry, just getting into the world of ASTs)

**Comment by retrohacker** [comment]
Also, thank you for such a quick response :heart:

**Comment by not-an-aardvark** [comment]
The code generator is making a decision about whether to include a linebreak after a `return` keyword in the generated code. If it chooses to do that, it should parenthesize the `return` argument. Otherwise, it doesn't need to parenthesize it, regardless of whether there were parentheses in the original source text before it was parsed.
