### ISSUE TITLE
Readme/documentation updates around ESLint comment attachment strategy

### ISSUE THREAD

**Issue by platinumazure** [eslint/espree#378]
I see two locations in the README.md that potentially need to be changed due to ESLint's new comment attachment strategy (i.e., ESLint attaches comments itself and we no longer rely on espree to do it for us):

* Line 110: Is this statement still true? Did comment attachment *in espree* change in later versions than 2.x?
* Line 128: ESLint doesn't rely on espree's comment attachment anymore

(N.B. All line locations are based on commit 56c5a9c7fb01bd7ba338d16c1c63d89d5b8ee8b6, which is current as of the creation time for this issue.)

Also, should we consider adding a note that ESLint no longer uses comment attachment from espree and whether that has any implications on if we continue to support a comment attachment strategy in espree?

**Comment by not-an-aardvark** [comment]
Regarding the first question, I think comment attachment in espree hasn't changed (we just toggled the option for it in ESLint).

Personally, I would be fine with removing comment attachment from espree given that ESLint no longer uses it.

**Comment by kaicataldo** [comment]
I would love to remove comment attachment (and am happy to make a PR). I wonder if this is something we should discuss in our next TSC meeting, since it's a pretty big breaking change as far as the parser goes.

**Comment by platinumazure** [comment]
@kaicataldo I would love to discuss it in a TSC meeting, but I'm wondering if we could create a new issue? This issue was originally about documentation updates that might be needed in espree's README. Thanks!

**Comment by kaicataldo** [comment]
Done! https://github.com/eslint/espree/issues/394
