### ISSUE TITLE
strange parsing errors since 4.1.0

### ISSUE THREAD

**Issue by quarterto** [eslint/espree#393]
eslint depends on `espree@^4.0.0`, which pulls in 4.1.0 on a fresh install. since installing this version, we've been getting strange `Parsing error`s on perfectly normal JSX syntax, e.g. in this build https://circleci.com/gh/Financial-Times/x-dash/1197. the referenced lines [aren't anything weird](https://github.com/Financial-Times/x-dash/blob/master/components/x-increment/__tests__/x-increment.test.jsx#L8). our [`.eslintrc.js`](https://github.com/Financial-Times/x-dash/blob/master/.eslintrc.js) includes a few plugins, including `eslint-plugin-react`, but is otherwise quite minimal.

when running `npm install`, i did note that it output:

```
npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-jsx@5.0.0
```

even though `espree` includes `acorn@^6.0.0` in its dependencies. seems like this _might_ be a cause, if it's using an incompatible version of acorn from somewhere?

**Comment by s100** [comment]
Reproduction of error:

```js
require('espree').parse("<div a='b' />", { ecmaFeatures: { jsx: true } })
```

In `espree@4.0.0` this returns a parse tree, in `espree@4.1.0` it throws a "SyntaxError: Unexpected token =" at line 1, index 6.

**Comment by not-an-aardvark** [comment]
cc @mysticatea

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. However, I can't seem to reproduce this issue (using Node v11.0.0):

```
$ npm i espree@4.1.0
npm WARN enoent ENOENT: no such file or directory, open '/path/to/espree-bug/package.json'
npm WARN espree-bug No description
npm WARN espree-bug No repository field.
npm WARN espree-bug No README data
npm WARN espree-bug No license field.

+ espree@4.1.0
added 4 packages from 2 contributors in 0.906s
found 0 vulnerabilities

~/path/to/espree-bug$ node
> require('espree').parse("<div a='b' />", { ecmaFeatures: { jsx: true } })
Node {
  type: 'Program',
  start: 0,
  end: 13,
  body:
   [ Node {
       type: 'ExpressionStatement',
       start: 0,
       end: 13,
       expression: [Node] } ],
  sourceType: 'script' }
```

What versions of `acorn` and `acorn-jsx` do you have installed with espree? When I installed `espree@4.1.0`, `acorn@6.0.2` and `acorn-jsx@5.0.0` were installed along with it.

**Comment by debugwand** [comment]
digging into node_modules after removing and re-installing,

* `acorn@6` is referenced as a devDependency of `acorn-jsx` 
* however, `node_modules/acorn` is version 5. It is required in JSDOM's dependencies as `"acorn": "^5.5.3",`
* JSDOM is version 11, and I've chased that back through the dependency tree as coming in as a result of Jest v23 (if you're using JSX there's a good chance your using Jest)

**Comment by not-an-aardvark** [comment]
I think this is a result of the same npm bug that was discussed in https://github.com/eslint/eslint/pull/10022.

**Comment by jvswatson** [comment]
To confirm the npm dependency issue, we ran into this problem and discovered that we had an unused dev dependency with `blanket`, which would install `acorn@1.2.2`, so the `espree` dependencies would then grab `acorn-jsx@5.0.0` and not `acorn`.  Removing the reference to `blanket` in `package.json` immediately got our tests running again.  Anyone else seeing this issue might try looking to see where else npm is deciding to install `acorn` and seeing if that can be removed/tweaked.

**Comment by mysticatea** [comment]
Looks like a bug in npm's installation logic. `espree@4.1.0` has the dependencies `acorn@^6.0.2` and `acorn-jsx@^5.0.0`, but npm didn't look to set up those correctly.

I could reproduce it with `npm@6.2.0`:

1. `rm -rf node_modules`
2. `npm i blanket eslint`
3. `npm ls espree acorn acorn-jsx`

```
+-- blanket@1.2.3
| +-- acorn@1.2.2
| `-- falafel@1.2.0
|   `-- acorn@1.2.2  deduped
`-- eslint@5.7.0
  `-- espree@4.1.0
    `-- acorn-jsx@5.0.0
```

Looks `acorn@6.x` is lost.

**Comment by s100** [comment]
As a workaround I've found that explicitly adding 

```
    "acorn": "^6.0.2",
    "acorn-jsx": "^5.0.0",
    "espree": "^4.1.0",
```

to my `package.json`'s `devDependencies` forces all three packages to be installed at the top level of `node_modules`, where they can find one another.

**Comment by keenwon** [comment]
I also encountered this problem, any updated status on this?

**Comment by mysticatea** [comment]
No. We are awaiting. This is `npm`'s bug and the `npm` CLI team has a plan to fix the bug by Summer in 2019.

**Comment by ljharb** [comment]
Still, since some change in eslint’s dep tree triggered it, surely there’s something eslint could do to reverse it in the meantime?

**Comment by ljharb** [comment]
(like, switch to require espree `~4.0`)

**Comment by mysticatea** [comment]
No.

>I don't think the revert makes sense. This causes by acorn's breaking change. Currently, the npm's bug appears when there is a older acorn in another dependency. After reverting, it will appear when there is a newer acorn in another dependency.
> https://github.com/eslint/eslint/issues/11018#issuecomment-438737502

**Comment by martijnsenden** [comment]
> No. We are awaiting. This is `npm`'s bug and the `npm` CLI team has a plan to fix the bug by Summer in 2019.

Any news on this?
