### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by mysticatea** [eslint/espree#398]
https://travis-ci.org/eslint/espree/builds/450505836

I guess https://github.com/acornjs/acorn/commit/94e8ad610baf8188a8289432a4e41afab6138bc3 caused this failure. We have to tweak our tests.

**Comment by Aladdin-ADD** [comment]
ops, I should have found the issue before merging. ψ(._. )>

working on this.

**Comment by not-an-aardvark** [comment]
This is also affecting the ESLint test suite (e.g. [here](https://travis-ci.org/eslint/eslint/jobs/450967698)).

**Comment by mysticatea** [comment]
Thank you, @Aladdin-ADD.
I think that predicting this kind of CI failure is difficult. :innocent:
