### ISSUE TITLE
Modules/Plugins for espree

### ISSUE THREAD

**Issue by IdkGoodName** [eslint/espree#402]
What about espree plugins/modules?

Acorn already has plugins.

```js
const newParser = acorn.Parser.extend(/*plugin1*/, /*plugin2*/)
newParser.parse(code) // Now it parses with plugin1 and plugin2
```

What about having it also in espree?

I like espree more than Acorn and I am being honest here. I would like to see plugin support for espree.

Thanks. 😄

**Comment by kaicataldo** [comment]
Related: https://github.com/eslint/espree/issues/334

**Comment by nzakas** [comment]
I'd prefer not to pursue this. Even though Espree is currently built on top of Acorn, that hasn't always been the case (it was originally a standalone parser) and may not continue to be the case in the future. Creating a plugin system would then mean creating something generic enough that it would still be useful if we decided to swap out Acorn for something else, which in turn would limit our options for Espree architecture going forward.
