### ISSUE TITLE
Lines are calculated wrong when relying on ASI

### ISSUE THREAD

**Issue by lo1tuma** [eslint/espree#41]
Given the following example:

```js
a()
```

gives the following `loc` for the `Programm` AST node:

```json
"loc": {
    "start": {
        "line": 1,
        "column": 0
    },
    "end": {
        "line": 1,
        "column": 3
    }
}
```

if you have an extra line break

```js
a()


```
 
you get the following `loc`:

```json
"loc": {
    "start": {
        "line": 1,
        "column": 0
    },
    "end": {
        "line": 2,
        "column": 0
    }
}
```

Each extra line will increase `loc.end.line`

```js
a()







```

```json
"loc": {
    "start": {
        "line": 1,
        "column": 0
    },
    "end": {
        "line": 8,
        "column": 0
    }
}
````

But if you use a semicolon after the `CallExpression` you will get a different `loc` for `Program` even if you have multiple empty lines:

```js
a();







```

```json
"loc": {
    "start": {
        "line": 1,
        "column": 0
    },
    "end": {
        "line": 1,
        "column": 4
    }
}
```

**Comment by lo1tuma** [comment]
[Related esprima issue](https://code.google.com/p/esprima/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&groupby=&sort=&id=541)

**Comment by nzakas** [comment]
Ah yes, I've run into this as well. I'll need to dig into the spec a bit to figure out the right thing to do (I'm not sure if ASI means the semicolon is inserted at the end of input in this case or immediately after the paren).

**Comment by btmills** [comment]
This annoyed me as I was working on the token API, but I looked at the [spec's rules for ASI](http://www.ecma-international.org/ecma-262/5.1/#sec-7.9.1), which seem to indicate that this is the correct behavior.

> a semicolon is automatically inserted before the offending token

Then in an example,

```js
{ 1
2 } 3
```

gets transformed into

```js
{ 1
;2 ;} 3;
```

**Comment by btmills** [comment]
And more relevant to this case in particular:

> When, as the program is parsed from left to right, the end of the input stream of tokens is encountered and the parser is unable to parse the input token stream as a single complete ECMAScript Program, then a semicolon is automatically inserted **at the end of the input stream**.

(Emphasis mine)

**Comment by nzakas** [comment]
Thanks for the research, that matched up with my expectation. So it seems like we are doing the right thing in this case.

**Comment by lo1tuma** [comment]
Thanks for the clarification :beers:.

**Comment by dmitriiabramov** [comment]
is this still considered the right behavior?
https://github.com/jquery/esprima seems to not have this issue any more

```js
a()





```


```json
{
    "loc": {
        "start": {
            "line": 1,
            "column": 0
        },
        "end": {
            "line": 1,
            "column": 3
        }
    },
    "type": "Program",
    "body": [
        {
            "loc": {
                "start": {
                    "line": 1,
                    "column": 0
                },
                "end": {
                    "line": 1,
                    "column": 3
                }
            },
            "type": "ExpressionStatement",
            "expression": {
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 0
                    },
                    "end": {
                        "line": 1,
                        "column": 3
                    }
                },
                "type": "CallExpression",
                "callee": {
                    "loc": {
                        "start": {
                            "line": 1,
                            "column": 0
                        },
                        "end": {
                            "line": 1,
                            "column": 1
                        }
                    },
                    "type": "Identifier",
                    "name": "a"
                },
                "arguments": []
            }
        }
    ],
    "sourceType": "script"
}
```

**Comment by dmitriiabramov** [comment]
the problem that i found is that when `comment` option is set to true, the comment range overlaps with node ranges and it's very hard to identify where the comment belongs to
e.g.
```js
// nodes
{
  type: 'Identifier',
  range: [20, 36]
}
/// comments
{
  type: 'Line',
  range: [25, 36]
```
