### ISSUE TITLE
Recognize deprecated "for each in"

### ISSUE THREAD

**Issue by retorquere** [eslint/espree#410]
I'm looking to write a rule that recognizes [for each in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for_each...in) so I can report it as an error, but espree doesn't recognize the construct. I've seen some talk in the issues of espree plugins but it seems that has stalled. Is there another way to get espree to recognize this so it can be reported cleanly?

**Comment by nzakas** [comment]
I'm sorry, we don't have a way to support this. `for-each-in` was never part of ECMAScript, but rather, was part of ECMAScript for XML, which we don't support.

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
