### ISSUE TITLE
jQuery Foundation adopts Esprima

### ISSUE THREAD

**Issue by jokeyrhyme** [eslint/espree#42]
So, this happened:
http://blog.jquery.com/2015/01/26/jquery-foundation-adopts-esprima/

How does this affect the Espree project? Are pull requests against Esprima more likely to be merged? Is it worth reaching out to the Esprima project to try to coordinate a merge?

Is Espree to Esprima as io.js is to node.js?

**Comment by nzakas** [comment]
As of right now, this doesn't affect what Espree is doing. We are going to continue working towards ES6 support. 

Whether or not Espree is ultimately folded back into Esprima is something that is yet to be determined. It really depends on the direction of Esprima as compared to the direction we're going in for Espree. If the directions are compatible, then I'll work to merge them back together; if they're not compatible, then we'll continue working on Espree separately.
