### ISSUE TITLE
Acorn dependency has a vulnerability on version v7.1.0

### ISSUE THREAD

**Issue by hugoluchessi** [eslint/espree#435]
# Problem
According to https://www.npmjs.com/advisories/1488, this version of acorn has a vulnerability.

# Solution
Bump it to version v7.1.1.

**Comment by kaicataldo** [comment]
Thanks for reporting this. While it’s not a bad idea to update the package.json, the current range in our `package.json` does support this. It also looks as though this is only an issue when Espree is used as a runtime dependency for a Node service, which I think is fairly infrequent.
