### ISSUE TITLE
Convert source code into TypeScript

### ISSUE THREAD

**Issue by g-plane** [eslint/espree#437]
Should we consider converting the source code of this project into TypeScript? We can leverage type checking with TypeScript. Also, `.d.ts` files can be generated for downstream users when compiling.

It may take long time to do this coversion, so we can enable `allowJs` and start progressive conversion.

**Comment by kaicataldo** [comment]
I'm generally :-1: for this proposal, particularly since we're not using TypeScript in ESLint core. 

Relevant PR: https://github.com/eslint/eslint/pull/12082

**Comment by nzakas** [comment]
I agree with @kaicataldo. I’d like ESLint to remain pure JavaScript to enable us to best test ESLint on itself.

**Comment by g-plane** [comment]
Hey, this is espree, not ESLint.

**Comment by nzakas** [comment]
Espree is part of the ESLint project.

**Comment by simonbuchan** [comment]
Note that webpack is using typescript in --checkJs to get at least some typechecking without needing a build step. Not sure if that matters to you.

**Comment by nzakas** [comment]
We aren't going to move forward with this, so closing.
