### ISSUE TITLE
Support to parse field declaration in classes

### ISSUE THREAD

**Issue by Iswaryasl** [eslint/espree#450]
Getting an parse error when trying to parse the below the code

  `class Rectangle {
            height = 0;
             width;
   }`

The class fields proposal is currently in Stage 3, and some latest browser also provides the support for the same,
It is already implemented in some other AST parsers (like babel).

So i am eagerly waiting for this support in espree.
Thanks.

**Comment by kaicataldo** [comment]
We implement syntax in the default parser once it reaches stage 4, so we won't be able to implement this quite yet. `@babel/eslint-parser` should do the trick in the meantime!
