### ISSUE TITLE
Release with Acorn 8.x

### ISSUE THREAD

**Issue by robpalme** [eslint/espree#484]
Hello friends,

[Espree now uses Acorn 8.x](https://github.com/eslint/espree/pull/473) on main, which is excellent, but I don't think it has shipped yet in an Espree release (latest is v7.3.1)

This upgrade is particularly useful because [Acorn 8.2.0 brings support for new JS syntax (class fields)](https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#820-2021-04-24) to ESLint. Will there be a new release of Espree soon? Correspondingly, if you are looking for any help to unblock this release, please say. Otherwise feel free to close this if pings like this are not desired.

**Comment by nzakas** [comment]
The next release is pending resolution of this issue: https://github.com/eslint/espree/issues/472

**Comment by robpalme** [comment]
Thank you for the guidance @nzakas - I have [opened a PR](https://github.com/acornjs/acorn/pull/1029) to fix Acorn.

**Comment by aladdin-add** [comment]
I don't think #472 is blocking the release of espree v8.0.

it is a minor bug, and bugfixes can be landed in later patch/minor releases.
