### ISSUE TITLE
Allow ecmaVersion: latest

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#495]
As of v8.0.0, Acorn now allows ecmaVersion: latest, which automatically sets ecmaVersion to the latest available version implemented.

Can we also allow this for Espree?

**Comment by aladdin-add** [comment]
to clarify: `ecmaVersion: "latest"` is as the same as `ecmaVersion: require("espree").latestEcmaVersion`. not passing the "latest" to acorn options?

**Comment by nzakas** [comment]
No, Acorn supports “latest” so we can pass that directly through from Espree.

**Comment by mysticatea** [comment]
How about making the `latest` as default?

I'm not sure if ES5 is the most popular environment now. Plus, [eslint-plugin-es](https://eslint-plugin-es.mysticatea.dev/) or something like provides more readable errors instead of "unexpected token" if people want to restrict to an old environment.

**Comment by aladdin-add** [comment]
> How about making the `latest` as default?
> 
> I'm not sure if ES5 is the most popular environment now. Plus, [eslint-plugin-es](https://eslint-plugin-es.mysticatea.dev/) or something like provides more readable errors instead of "unexpected token" if people want to restrict to an old environment.

As of now, I don't think we can go that far. maybe we can reconsider it after the "latest" option get landed.

**Comment by aladdin-add** [comment]
> No, Acorn supports “latest” so we can pass that directly through from Espree.

* espree has exported a latestEcmaVersion;
* acorn option "latest" is `1e8` https://github.com/acornjs/acorn/blob/43c989c9898b1a8c70eeae0f4728f3255825b05a/acorn/src/options.js#L103-L104

it could cause potential confusing if these two values are not equal.

**Comment by nzakas** [comment]
@aladdin-add what problems are you thinking of? The value inside Acorn doesn’t have any effect on ESLint. 

I think changing the default to latest makes sense. This should not affect ESLint because we are manually setting ecmaVersion in ESLint itself.

**Comment by aladdin-add** [comment]
class fields - it has been supported in acorn v8.2.0, but not for espree yet (https://github.com/eslint/espree/pull/486 has not been merged & released).

**Comment by mysticatea** [comment]
Yes. #486 updates `latestEcmaVersion` ([tests/lib/supported-ecmaversions.js](https://github.com/eslint/espree/pull/486/files#diff-154206e7b88b886b0a66631caf3a1928bb7ac8b2f60e0810905fd0053ca4ec10)). It comes from the last value of `supportedEcmaVersions`. Therefore, we cannot support new ecma versions unless `latestEcmaVersion` update.

**Comment by nzakas** [comment]
Initial implementation here: https://github.com/eslint/espree/pull/499

Note: this issue isn't yet accepted, so I just sent the PR as a draft for now.

**Comment by mdjermanovic** [comment]
> No, Acorn supports “latest” so we can pass that directly through from Espree.

Just to double-check, as it isn't clear from the discussion - we decided to pass Espree's `latestEcmaVersion` (number) instead of  `"latest"` to Acorn?

**Comment by mdjermanovic** [comment]
> I think changing the default to latest makes sense. This should not affect ESLint because we are manually setting ecmaVersion in ESLint itself.

If user doesn't specify `parserOptions.ecmaVersion` in their ESLint config, ESLint will pass `ecmaVersion: undefined` to Espree, so in that case Espree's default applies. This change would be then a breaking change for ESLint users (default for `ecmaVersion` changes from `5` to the latest).

**Comment by mdjermanovic** [comment]
Do we intend to allow specifying `ecmaVersion: "latest"` in ESLint config? I think that's the idea in [rfcs#79 - 3. Remove the usage of eslint & espree](https://github.com/eslint/rfcs/blob/346a6aff1bd1e52006f19991b5762453d5677c9e/designs/2021-init-command-eslint-cli/README.md#3-remove-the-usage-of-eslint--espree).

A problem with `ecmaVersion: "latest"` is that `eslint-scope` also expects `ecmaVersion`. ESLint calls `eslintScope.analyze` with `parserOptions.ecmaVersion` from the configuration (or `5` if it wasn't specified).

https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L607-L620

If we pass `"latest"` from ESLint, scope will be analyzed as if it was `ecmaVersion: 3`.

**Comment by aladdin-add** [comment]
sound we should explicitly normalize the `ecmaVersion` to 5 (if not specified).

as for "latest", we have 2 choices:
* convert `"latest"` to `espree.latestEcmaVersion`, and passing it to `eslintScope.analyze`
* pass "latest" to `eslintScope.analyze` (it need updates to allow the value)

**Comment by nzakas** [comment]
Yes, the idea is to allow "latest" in ESLint configs eventually, but that doesn't have to be done along with this change in Espree. We can always address that later and just make sure that ESLint defaults to `ecmaVersion: 5` when no other setting is present. We don't have to allow "latest" right away in ESLint (I'm pretty sure it will be a validation error right now).

The value for `ecmaVersion` in `eslint-scope` is only to enable `let`/`const` block-scope evaluations. It just checks if [`ecmaVersion > 5`](https://github.com/eslint/eslint-scope/blob/ae27ff3692ab13cf62075b8659f0e17dfa44acd1/lib/scope-manager.js#L80). As @aladdin-add pointed out, we can always normalize "latest" in ESLint to `espree.latestEcmaVersion` to avoid that.

I don't think any of this should block enabling "latest" for Espree, though.

**Comment by aladdin-add** [comment]
to allow "latest" in ESLint configs, this is not a must. I made a PR to implement it: https://github.com/eslint/eslint/pull/14622

**Comment by mdjermanovic** [comment]
I support both `"latest"` and changing the default to latest (assuming that we will update ESLint to keep `ecmaVersion: 5` as ESLint's default) :+1:
