### ISSUE TITLE
Parsing Nashorn Extensions

### ISSUE THREAD

**Issue by bmix** [eslint/espree#500]
This is not about running JSLint/Espree *on* the Nashorn host, but about parsing JS code written *for* Nashorn.

While Nashorn (ES for JVM, followup to Rhino) has been deprecated, it comes back in the ECMAScript implementation for GraalVM by means of a runtime configuraiton. JS on the JVM has a lot of uses, the one I am using it for, is to prototype Java code (this saves the many repeated build/deploy processes during development). But it's also a great shell scripting language!

I realized, that ESLint does error out because of something like:

```js
// this extension makes it easy to loop over Java collection types
for each (let currentKey in allKeys) {
  ...
}
```

Could Nashorn extensions be implemented or, at least, an *ignore* option be added to the parser, so it doesn't stop parsing at first sight?

[An overview of Nashorn extensions is here.](https://wiki.openjdk.java.net/display/Nashorn/Nashorn+extensions)

Thank you.

**Comment by aladdin-add** [comment]
espree is not designed to parse non-js code. But eslint supports 3rd party parsers, you can write a custom parser to support it. https://eslint.org/docs/developer-guide/working-with-custom-parsers

**Comment by nzakas** [comment]
Yeah, I’m sorry, we aren’t going to go back and implement parsing for nonstandard syntax. A custom parser is your best bet.
