### ISSUE TITLE
Drop Node v10/v13/v15 support

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/espree#501]
Since we are not planning to use Espree v8 in ESLint v7, can we align `engines.node` in `package.json` with ESLint v8 (https://github.com/eslint/eslint/pull/14592)?

**Comment by aladdin-add** [comment]
and some other repos:
* eslint/eslintrc
* eslint/eslint-scope (I would suggest not to change it, as is used by webpack, which supports Node v10)
* eslint/eslint-visitor-keys

**Comment by nzakas** [comment]
Makes sense.

**Comment by snitin315** [comment]
I will do it 👍🏻
