### ISSUE TITLE
It's make me confuse: engines ->"node": "^12.22.0

### ISSUE THREAD

**Issue by rhinonan** [eslint/espree#508]
Why not node: ^12.0.0

This will caused many project install dependencies  to fail

**Comment by coastman** [comment]
Why not node: ^12.19.1

**Comment by bmish** [comment]
Might be so that the package can be converted to ESM: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-move-my-commonjs-project-to-esm

**Comment by nzakas** [comment]
Yes, this is because we want to use ESM going forward. See the discussion at https://github.com/eslint/eslint/issues/14023#issuecomment-839380175
