### ISSUE TITLE
Node 15 isn't supported for v8?

### ISSUE THREAD

**Issue by silverbucket** [eslint/espree#511]
Updating dependencies for my project, and compliance is failing when testing on node 15 due to espree v8:

```
error espree@8.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.14.0"
```

Is there a reason for this? Will it actually not work when running on node 15?

**Comment by bmish** [comment]
It will likely still work with Node 15 at this point but officially we don't support that anymore. Odd-numbered Node releases shouldn't really be used in production so you'll likely want to upgrade to Node 16: https://nodejs.org/en/about/releases/

**Comment by silverbucket** [comment]
Hi @bmish - I guess this is a limitation in the way package.json defines node versions. We build for node 16, but keep tests for the latest 3 versions running (eg. 14, 15, 16). Updating dependencies that use espree v8 causes compliance to fail during `yarn install`, even though it would probably work fine.

**Comment by nzakas** [comment]
We regularly remove formal support when Node.JS EOLs particular versions. There’s no reason to believe ESLint v8.0.0 won’t work on Node.JS 15, we just won’t be making changes to address any compatibility problems.

**Comment by bmish** [comment]
It's pretty standard practice among NPM packages to only support the active LTS versions of Node (currently, that's Node 12, 14, 16, and anything higher for flexibility). Many other popular NPM packages have already moved to the same list of supported Node versions as ESLint v8.

My personal advice for you:

Regarding running linting: technically, it's likely sufficient to run your internal project linting against your primary Node version *only* (which it sounds like is Node 16).

Regarding running tests in general:
* If your project is an app running on Node 16, then you only really need to test on Node 16 at this point (you could start testing higher versions once they come out).
* If your project is a library, then you would want to test against any Node versions it supports.

**Comment by silverbucket** [comment]
Thanks everyone, yes we've decided to remove testing for 15, and going forward we will add compliance checks and integration testing for odd versions only as long as they are active, remove them as soon as the next LTS is released.
