### ISSUE TITLE
ChainExpression and others are missing in espree.Syntax

### ISSUE THREAD

**Issue by codeworrior** [eslint/espree#531]
According to #331, the `espree.Syntax` object is supposed to contain all node types supported by Espree. But comparing it with ` espree.VisitorKeys`, the following node types are missing:

* `ChainExpression`
* `ImportExpression`
*  `JSXFragment`
*  `JSXOpeningFragment`
*  `JSXClosingFragment`
*  `PrivateIdentifier`
*  `PropertyDefinition`
*  `StaticBlock`

`ExperimentalRestProperty` and `ExperimentalSpreadProperty` are also missing, but this might be intentional.

For sure one could derive a list of node types from the keys of `VisitorKeys`, but what's the purpose of the `Syntax` export then? Shouldn't it be used any longer?

**Comment by nzakas** [comment]
This was copied over for Esprima compatibility back in the beginning. It appears we haven’t done a good job of keeping it updated. We should probably just base it off of VisitorKeys so the two are always in sync. Would you be interested in submitting a PR for that?
