### ISSUE TITLE
vague misleading licensing grant in test files with V8 project as copyright holder

### ISSUE THREAD

**Issue by jonassmedegaard** [eslint/espree#537]
Git commit 93b24dd introduced files `tests/fixtures/ecma-version/13/class-static-blocks/*` where `*.src.js^ files contain the following header:
```JavaScript
// Copyright (C) 2021 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
```

This project includes a file `LICENSE` which contains a BSD-2-Clause license, but I strongly suspect that the license intended by that copyright holder is instead the same derived BSD-3-Clause license as used for the test262 project (a variant explicitly mentioning Ecma International in 3rd clause).

Please clarify licensing - e.g. by Including a file `tests/fixtures/ecma-version/13/class-static-blocks/LICENSE` with same content as https://github.com/tc39/test262/blob/main/LICENSE

**Comment by nzakas** [comment]
Yeah, looks like we missed that file. Can you open a pull request to add it?
