### ISSUE TITLE
as token type: Identifier -> Punctuator

### ISSUE THREAD

**Issue by conartist6** [eslint/espree#553]
In the code:
```js
import { foo as bar } from 'source'; 
```
`as` is an `Identifier` token. I believe this is incorrect, since `as` can never refer to a value of any kind. I would expect `as` to be a `Punctuator` token.

[Here](https://astexplorer.net/#/gist/14d4e2a7341903c5317fbc1d74509197/63a84b34deaa97e2cc5567aca1c06566b9f271bc) is the example in astexplorer.

**Comment by conartist6** [comment]
Interestingly `of` is considered an identifier too in `for (const foo of bar)`

**Comment by nzakas** [comment]
Yup, this is just one of the quirks of working with JavaScript tokenization. We follow the original approach that Esprima took, which is that known keywords are of type Keyword, other words are type Identifier, and only non-word symbols are Punctuators. We can’t change that now without breaking the ecosystem.

**Comment by conartist6** [comment]
Alrighty. I think I'm going to do something different in `cst-tokens` since I don't have any ecosystem-breaking burden. Maybe I'll introduce something like `type: 'Word'` to avoid diluting the meaning of `type: 'Keyword'`.
