### ISSUE TITLE
How to use from a script tag?

### ISSUE THREAD

**Issue by amark** [eslint/espree#555]
I'm currently using esprima, thinking about upgrading to espree - thanks for your work!

I just spent the last hour trying every variation of skypack/esm.run, esm-to-cjs, etc. that I could possibly find.

For the life of me, I can't get espree to work. Nor can I find an online demo of it.

All I'm trying to do is download an offline copy of it that I can use in an index.html file (no build, no tools, no modules).

Please help? Thanks!

**Comment by nzakas** [comment]
We don't officially support browser runtimes for Espree, but you should be able to do this:

```js
import espree from 'https://cdn.skypack.dev/espree';

const ast = espree.parse("foo");
console.log(ast);
```
