### ISSUE TITLE
Not able to access parent node from current node.

### ISSUE THREAD

**Issue by dharmarajrdr** [eslint/espree#559]
var a = {
     b : function(){
          this.c();    // equals to a.c();
     },
     c : function(){
          console.log('method c');
     }
}
**Purpose** : Say for example, my current node's type is "ThisExpression" inside . Now, I want to replace 'this' with its actual name( here it is 'a' ).

**Comment by dharmarajrdr** [comment]
Need a property 'parent' which points to its parent node.

**Comment by nzakas** [comment]
This is intentional. Espresso produces a raw AST. You need to add additional properties yourself if you want them.
