### ISSUE TITLE
support destructured params w/defaults (shorthand syntax)

### ISSUE THREAD

**Issue by xjamundx** [eslint/espree#56]
While support for destructuring was added in #51 none of these cases work:
- `function a({x = 10}) {}` 
- `function a({x = 10, y: { z = 10 }}) {}`
- `({x = 10}) => x`
- `({x = 10, y: { z = 10 }}) => [x,y]`
- `[a=10] = 0`
- `var {a = 10} = {}`

Latest spec can be found here:
https://github.com/estree/estree/issues/13

**Comment by xjamundx** [comment]
Will spend like 40 minutes trying to get this to work and see what I can come up with...

**Comment by nzakas** [comment]
Cool. Just as an FYI, I'm looking at how we can potentially merge back into Esprima now that it's moving again. I won't stop you if you want to tackle this, just wanted to give to all the info before you spend more time.

**Comment by xjamundx** [comment]
That's great news, we'll see how far along I get. It's good learning :)

**Comment by xjamundx** [comment]
Related https://github.com/jquery/esprima/issues/1028

**Comment by xjamundx** [comment]
Will try to take another stab at this sometime later this week...
