### ISSUE TITLE
Set up release-please

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#563]
We are moving to release-please for most of our repos, so we need to get it set up here.

Additional non-code setup:

- [x] Update [organization Actions secrets][1] to give this repository access to `NPM_TOKEN`, `MASTODON_ACCESS_TOKEN`, and the four `TWITTER_*` secrets.
- [x] Update [repository Actions settings][2] to "Allow GitHub Actions to create and approve pull requests".
- [ ] Update [npm package settings][3] to allow publishing with 2FA **or** automation or granular access tokens.

[1]: https://github.com/organizations/eslint/settings/secrets/actions
[2]: https://github.com/eslint/espree/settings/actions
[3]: https://www.npmjs.com/package/@eslint/espree/access

See https://github.com/eslint/create-config/pull/54 as an example.

**Comment by btmills** [comment]
Working on this.
