### ISSUE TITLE
Set up scripts/lint-staged to match those in eslint repo

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#564]
We should set up the npm scripts and lint-staged in this repo to match the `eslint` repo.

Conventions are listed here:
https://github.com/eslint/eslint/blob/main/docs/src/contribute/package-json-conventions.md

@pmcelhaney are you still interested in doing this for other repos?

**Comment by pmcelhaney** [comment]
Yes, but I'm afraid I'm pulled in too many different directions now and not sure when I'll be able to get to it. Happy to let someone else take it.

**Comment by nzakas** [comment]
Okay, thanks. We'll see if we can get someone else to help out.

**Comment by amareshsm** [comment]
It looks like it is already done. Anything else pending here?
