### ISSUE TITLE
Support for `using` keyword

### ISSUE THREAD

**Issue by fregante** [eslint/espree#586]
I don't see any commits related to this so I think this keyword is not supported yet. I created an issue in the eslint repo to track it, but I think it has to be fixed here, so I'm opening it for visibility.

Sample code:

```js
{
  const getResource = () => {
    return {
      [Symbol.dispose]: () => {
        console.log('Hooray!')
      }
    }
  }
  using resource = getResource();
}
```

Related:

- https://github.com/eslint/eslint/issues/17701
- TypeScript 5.2 already supports it: https://www.totaltypescript.com/typescript-5-2-new-keyword-using
- The proposal is at stage 3: https://github.com/tc39/proposal-explicit-resource-management

**Comment by mdjermanovic** [comment]
As stated in [What ECMAScript features do you support](https://github.com/eslint/espree#what-ecmascript-features-do-you-support), we are implementing features as they are finalized. When this proposal reaches stage 4, we'll add support for this syntax.
