### ISSUE TITLE
Not ES2020

### ISSUE THREAD

**Issue by weaweawe01** [eslint/espree#605]
espree.tokenize("alert(1n)")
Uncaught [SyntaxError: Identifier directly after number
] {
  index: 7,
  lineNumber: 1,
  column: 8
}

**Comment by aladdin-add** [comment]
bigint is supported, you need to pass the `ecmaVersion >= 2020` or `"latest"`.

```js
espree.tokenize("1n", {ecmaVersion: 2020});
```
