### ISSUE TITLE
Change Request: replace `npm-run-all` by `npm-run-all2`

### ISSUE THREAD

**Issue by Jayllyz** [eslint/espree#616]
### Which packages would you like to change?

- [X] `espree`

### What problem do you want to solve?

Basically, npm-run-all is no longer actively maintained and there's now a better maintained npm-run-all2 which is actually lighter, has security fixes, etc.
https://npmgraph.js.org/?q=npm-run-all#zoom=w&color=outdated

### What do you think is the correct solution?

https://npmgraph.js.org/?q=npm-run-all2#zoom=w&color=outdated
https://github.com/bcomnes/npm-run-all2

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sounds good. Feel free to open a PR.
