### ISSUE TITLE
Additional 3rd Party Scripts

### ISSUE THREAD

**Issue by xjamundx** [eslint/espree#68]
Here are a few ES6-based projects to consider adding to the 3rd party dir once we get module support:
https://github.com/facebook/immutable-js
https://github.com/emberjs/ember.js
https://github.com/babel/babel

So excited this is landing soon!
##

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
