### ISSUE TITLE
Support TryStatement.handler

### ISSUE THREAD

**Issue by btmills** [eslint/espree#69]
Ref estree/estree#1:

```js
interface TryStatement <: Statement {
    // ....
    handler: CatchClause | null;
    handlers: [ CatchClause ]; // Removed
    // ....
}
```

The `handlers` array on `TryStatement` nodes was replaced with a single `handler`, which may be either a `CatchClause` or `null`.

Presumably the best way to do this is to port jquery/esprima#1034, a backward-compatible change which adds `handler` and preserves `handlers`, then remove `handlers` as a breaking change later?

**Comment by nzakas** [comment]
Yup!
