### ISSUE TITLE
Remove TryStatement.handlers

### ISSUE THREAD

**Issue by btmills** [eslint/espree#71]
Ref estree/estree#1:

```js
interface TryStatement <: Statement {
    // ....
    handler: CatchClause | null;
    handlers: [ CatchClause ]; // Removed
    // ....
}
```

The `handlers` array on `TryStatement` nodes was replaced with a single `handler`, which may be either a `CatchClause` or `null`.

#70 added support for the singular `handler` property. The next step is to remove `handlers`. This will be a breaking change.

**Comment by nzakas** [comment]
We'll do this in v2.0.0

**Comment by nzakas** [comment]
Working on this.
