### ISSUE TITLE
Update module functionality

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#72]
* [x] add test to validate that `sourceType="module"` effectible enables strict mode (e.g.: `WithStatement` is invalid in modules)
* [x] `ImportDeclaration` and `ExportDeclaration` cannot be used inside functions (missing tests and implementation)
* [x] Enable classes for export and export default declarations (all TODOs are in the code, very straight forward)

**Comment by nzakas** [comment]
Looking at usage patterns, I think I'd also like to make a small change:

1. Add a `modules` feature flag that just enables import/export declarations and switches the parser into strict mode.
1. Make `sourceType = "module"` turn on every ES6 feature flag, including `modules`.

I think that gives us both parity with Esprima and the configurability some have asked for in ESLint.

**Comment by caridy** [comment]
ha, I told you so!, lets roll with that, should be flexible enough. I wonder if the inverse will be possible. Using `sourceType="module"` with `class` disabled. This is sort of a requirement that we have at Yahoo, where we want to focus on zero-cost abstraction features only rather than all. e.g.: we want to use modules but we don't want to use `let`.

**Comment by nzakas** [comment]
Yup, you were right.

I think in this model, you can use `sourceType="module"` and then set `classes` to false explicitly to achieve what you want.

**Comment by caridy** [comment]
:+1:

**Comment by nzakas** [comment]
I'll take a stab at the feature flag, then we can attack the other pieces.

**Comment by xjamundx** [comment]
Oh I have PRs for the last 2 I can open I think...not sure how I missed this thread!

**Comment by nzakas** [comment]
Working on tests for sourceType="module"

**Comment by nzakas** [comment]
Wow, this is a really good test. Uncovered a few issues.

**Comment by nzakas** [comment]
All done!
