### ISSUE TITLE
Change rest parameters to implement ESTree

### ISSUE THREAD

**Issue by nzakas** [eslint/espree#84]
Rest parameters should now end up in a `RestElement` in a function's `params` array (see https://github.com/estree/estree/blob/master/es6.md#restelement). This would involve removing the `rest` property from all function types and would be a breaking change.

**Comment by xjamundx** [comment]
I can maybe take this in a few days if it's not urgent...

**Comment by nzakas** [comment]
Not urgent.

**Comment by nzakas** [comment]
Working on this.
