### ISSUE TITLE
Template Strings should disallow Legacy Octal Literals

### ISSUE THREAD

**Issue by mikesherov** [eslint/espree#96]
See https://github.com/mikesherov/esprima/commit/e7f1d03c847a737b1cbfb058e916f4392ad4e67b

as defined in: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literal-lexical-components the note says:

> A conforming implementation must not use the extended definition of EscapeSequence described in B.1.2 when parsing a TemplateCharacter.

**Comment by nzakas** [comment]
Thanks, will look into it.

**Comment by nzakas** [comment]
Working on this.
